### YamlMime:ManagedReference
items:
- uid: Godot.OpenXRInterface.PerfSettingsSubDomain
  commentId: T:Godot.OpenXRInterface.PerfSettingsSubDomain
  id: OpenXRInterface.PerfSettingsSubDomain
  parent: Godot
  children:
  - Godot.OpenXRInterface.PerfSettingsSubDomain.Compositing
  - Godot.OpenXRInterface.PerfSettingsSubDomain.Rendering
  - Godot.OpenXRInterface.PerfSettingsSubDomain.Thermal
  langs:
  - csharp
  - vb
  name: OpenXRInterface.PerfSettingsSubDomain
  nameWithType: OpenXRInterface.PerfSettingsSubDomain
  fullName: Godot.OpenXRInterface.PerfSettingsSubDomain
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum OpenXRInterface.PerfSettingsSubDomain : long'
    content.vb: Public Enum OpenXRInterface.PerfSettingsSubDomain As Long
- uid: Godot.OpenXRInterface.PerfSettingsSubDomain.Compositing
  commentId: F:Godot.OpenXRInterface.PerfSettingsSubDomain.Compositing
  id: Compositing
  parent: Godot.OpenXRInterface.PerfSettingsSubDomain
  langs:
  - csharp
  - vb
  name: Compositing
  nameWithType: OpenXRInterface.PerfSettingsSubDomain.Compositing
  fullName: Godot.OpenXRInterface.PerfSettingsSubDomain.Compositing
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Compositing = 0
    return:
      type: Godot.OpenXRInterface.PerfSettingsSubDomain
- uid: Godot.OpenXRInterface.PerfSettingsSubDomain.Rendering
  commentId: F:Godot.OpenXRInterface.PerfSettingsSubDomain.Rendering
  id: Rendering
  parent: Godot.OpenXRInterface.PerfSettingsSubDomain
  langs:
  - csharp
  - vb
  name: Rendering
  nameWithType: OpenXRInterface.PerfSettingsSubDomain.Rendering
  fullName: Godot.OpenXRInterface.PerfSettingsSubDomain.Rendering
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Rendering = 1
    return:
      type: Godot.OpenXRInterface.PerfSettingsSubDomain
- uid: Godot.OpenXRInterface.PerfSettingsSubDomain.Thermal
  commentId: F:Godot.OpenXRInterface.PerfSettingsSubDomain.Thermal
  id: Thermal
  parent: Godot.OpenXRInterface.PerfSettingsSubDomain
  langs:
  - csharp
  - vb
  name: Thermal
  nameWithType: OpenXRInterface.PerfSettingsSubDomain.Thermal
  fullName: Godot.OpenXRInterface.PerfSettingsSubDomain.Thermal
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Thermal = 2
    return:
      type: Godot.OpenXRInterface.PerfSettingsSubDomain
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.OpenXRInterface.PerfSettingsSubDomain
  commentId: T:Godot.OpenXRInterface.PerfSettingsSubDomain
  parent: Godot
  isExternal: true
  href: Godot.OpenXRInterface.html
  name: OpenXRInterface.PerfSettingsSubDomain
  nameWithType: OpenXRInterface.PerfSettingsSubDomain
  fullName: Godot.OpenXRInterface.PerfSettingsSubDomain
  spec.csharp:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsSubDomain
    name: PerfSettingsSubDomain
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsSubDomain.html
  spec.vb:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsSubDomain
    name: PerfSettingsSubDomain
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsSubDomain.html
