### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentFogMode
  commentId: T:Godot.RenderingServer.EnvironmentFogMode
  id: RenderingServer.EnvironmentFogMode
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentFogMode.Depth
  - Godot.RenderingServer.EnvironmentFogMode.Exponential
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentFogMode
  nameWithType: RenderingServer.EnvironmentFogMode
  fullName: Godot.RenderingServer.EnvironmentFogMode
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentFogMode : long'
    content.vb: Public Enum RenderingServer.EnvironmentFogMode As Long
- uid: Godot.RenderingServer.EnvironmentFogMode.Exponential
  commentId: F:Godot.RenderingServer.EnvironmentFogMode.Exponential
  id: Exponential
  parent: Godot.RenderingServer.EnvironmentFogMode
  langs:
  - csharp
  - vb
  name: Exponential
  nameWithType: RenderingServer.EnvironmentFogMode.Exponential
  fullName: Godot.RenderingServer.EnvironmentFogMode.Exponential
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Exponential = 0
    return:
      type: Godot.RenderingServer.EnvironmentFogMode
- uid: Godot.RenderingServer.EnvironmentFogMode.Depth
  commentId: F:Godot.RenderingServer.EnvironmentFogMode.Depth
  id: Depth
  parent: Godot.RenderingServer.EnvironmentFogMode
  langs:
  - csharp
  - vb
  name: Depth
  nameWithType: RenderingServer.EnvironmentFogMode.Depth
  fullName: Godot.RenderingServer.EnvironmentFogMode.Depth
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Depth = 1
    return:
      type: Godot.RenderingServer.EnvironmentFogMode
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentFogMode
  commentId: T:Godot.RenderingServer.EnvironmentFogMode
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentFogMode
  nameWithType: RenderingServer.EnvironmentFogMode
  fullName: Godot.RenderingServer.EnvironmentFogMode
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentFogMode
    name: EnvironmentFogMode
    isExternal: true
    href: Godot.RenderingServer.EnvironmentFogMode.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentFogMode
    name: EnvironmentFogMode
    isExternal: true
    href: Godot.RenderingServer.EnvironmentFogMode.html
