### YamlMime:ManagedReference
items:
- uid: Godot.Environment.AmbientSource
  commentId: T:Godot.Environment.AmbientSource
  id: Environment.AmbientSource
  parent: Godot
  children:
  - Godot.Environment.AmbientSource.Bg
  - Godot.Environment.AmbientSource.Color
  - Godot.Environment.AmbientSource.Disabled
  - Godot.Environment.AmbientSource.Sky
  langs:
  - csharp
  - vb
  name: Environment.AmbientSource
  nameWithType: Environment.AmbientSource
  fullName: Godot.Environment.AmbientSource
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.AmbientSource : long'
    content.vb: Public Enum Environment.AmbientSource As Long
- uid: Godot.Environment.AmbientSource.Bg
  commentId: F:Godot.Environment.AmbientSource.Bg
  id: Bg
  parent: Godot.Environment.AmbientSource
  langs:
  - csharp
  - vb
  name: Bg
  nameWithType: Environment.AmbientSource.Bg
  fullName: Godot.Environment.AmbientSource.Bg
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Bg = 0
    return:
      type: Godot.Environment.AmbientSource
- uid: Godot.Environment.AmbientSource.Disabled
  commentId: F:Godot.Environment.AmbientSource.Disabled
  id: Disabled
  parent: Godot.Environment.AmbientSource
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: Environment.AmbientSource.Disabled
  fullName: Godot.Environment.AmbientSource.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 1
    return:
      type: Godot.Environment.AmbientSource
- uid: Godot.Environment.AmbientSource.Color
  commentId: F:Godot.Environment.AmbientSource.Color
  id: Color
  parent: Godot.Environment.AmbientSource
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: Environment.AmbientSource.Color
  fullName: Godot.Environment.AmbientSource.Color
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Color = 2
    return:
      type: Godot.Environment.AmbientSource
- uid: Godot.Environment.AmbientSource.Sky
  commentId: F:Godot.Environment.AmbientSource.Sky
  id: Sky
  parent: Godot.Environment.AmbientSource
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: Environment.AmbientSource.Sky
  fullName: Godot.Environment.AmbientSource.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 3
    return:
      type: Godot.Environment.AmbientSource
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.AmbientSource
  commentId: T:Godot.Environment.AmbientSource
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.AmbientSource
  nameWithType: Environment.AmbientSource
  fullName: Godot.Environment.AmbientSource
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.AmbientSource
    name: AmbientSource
    isExternal: true
    href: Godot.Environment.AmbientSource.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.AmbientSource
    name: AmbientSource
    isExternal: true
    href: Godot.Environment.AmbientSource.html
