### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSdfgiyScale
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiyScale
  id: RenderingServer.EnvironmentSdfgiyScale
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSdfgiyScale.Scale100Percent
  - Godot.RenderingServer.EnvironmentSdfgiyScale.Scale50Percent
  - Godot.RenderingServer.EnvironmentSdfgiyScale.Scale75Percent
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSdfgiyScale
  nameWithType: RenderingServer.EnvironmentSdfgiyScale
  fullName: Godot.RenderingServer.EnvironmentSdfgiyScale
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSdfgiyScale : long'
    content.vb: Public Enum RenderingServer.EnvironmentSdfgiyScale As Long
- uid: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale50Percent
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiyScale.Scale50Percent
  id: Scale50Percent
  parent: Godot.RenderingServer.EnvironmentSdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale50Percent
  nameWithType: RenderingServer.EnvironmentSdfgiyScale.Scale50Percent
  fullName: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale50Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale50Percent = 0
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiyScale
- uid: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale75Percent
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiyScale.Scale75Percent
  id: Scale75Percent
  parent: Godot.RenderingServer.EnvironmentSdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale75Percent
  nameWithType: RenderingServer.EnvironmentSdfgiyScale.Scale75Percent
  fullName: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale75Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale75Percent = 1
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiyScale
- uid: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale100Percent
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiyScale.Scale100Percent
  id: Scale100Percent
  parent: Godot.RenderingServer.EnvironmentSdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale100Percent
  nameWithType: RenderingServer.EnvironmentSdfgiyScale.Scale100Percent
  fullName: Godot.RenderingServer.EnvironmentSdfgiyScale.Scale100Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale100Percent = 2
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiyScale
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSdfgiyScale
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiyScale
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSdfgiyScale
  nameWithType: RenderingServer.EnvironmentSdfgiyScale
  fullName: Godot.RenderingServer.EnvironmentSdfgiyScale
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiyScale
    name: EnvironmentSdfgiyScale
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiyScale.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiyScale
    name: EnvironmentSdfgiyScale
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiyScale.html
