### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSsaoQuality
  commentId: T:Godot.RenderingServer.EnvironmentSsaoQuality
  id: RenderingServer.EnvironmentSsaoQuality
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSsaoQuality.High
  - Godot.RenderingServer.EnvironmentSsaoQuality.Low
  - Godot.RenderingServer.EnvironmentSsaoQuality.Medium
  - Godot.RenderingServer.EnvironmentSsaoQuality.Ultra
  - Godot.RenderingServer.EnvironmentSsaoQuality.VeryLow
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSsaoQuality
  nameWithType: RenderingServer.EnvironmentSsaoQuality
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSsaoQuality : long'
    content.vb: Public Enum RenderingServer.EnvironmentSsaoQuality As Long
- uid: Godot.RenderingServer.EnvironmentSsaoQuality.VeryLow
  commentId: F:Godot.RenderingServer.EnvironmentSsaoQuality.VeryLow
  id: VeryLow
  parent: Godot.RenderingServer.EnvironmentSsaoQuality
  langs:
  - csharp
  - vb
  name: VeryLow
  nameWithType: RenderingServer.EnvironmentSsaoQuality.VeryLow
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality.VeryLow
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: VeryLow = 0
    return:
      type: Godot.RenderingServer.EnvironmentSsaoQuality
- uid: Godot.RenderingServer.EnvironmentSsaoQuality.Low
  commentId: F:Godot.RenderingServer.EnvironmentSsaoQuality.Low
  id: Low
  parent: Godot.RenderingServer.EnvironmentSsaoQuality
  langs:
  - csharp
  - vb
  name: Low
  nameWithType: RenderingServer.EnvironmentSsaoQuality.Low
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality.Low
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Low = 1
    return:
      type: Godot.RenderingServer.EnvironmentSsaoQuality
- uid: Godot.RenderingServer.EnvironmentSsaoQuality.Medium
  commentId: F:Godot.RenderingServer.EnvironmentSsaoQuality.Medium
  id: Medium
  parent: Godot.RenderingServer.EnvironmentSsaoQuality
  langs:
  - csharp
  - vb
  name: Medium
  nameWithType: RenderingServer.EnvironmentSsaoQuality.Medium
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality.Medium
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Medium = 2
    return:
      type: Godot.RenderingServer.EnvironmentSsaoQuality
- uid: Godot.RenderingServer.EnvironmentSsaoQuality.High
  commentId: F:Godot.RenderingServer.EnvironmentSsaoQuality.High
  id: High
  parent: Godot.RenderingServer.EnvironmentSsaoQuality
  langs:
  - csharp
  - vb
  name: High
  nameWithType: RenderingServer.EnvironmentSsaoQuality.High
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality.High
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: High = 3
    return:
      type: Godot.RenderingServer.EnvironmentSsaoQuality
- uid: Godot.RenderingServer.EnvironmentSsaoQuality.Ultra
  commentId: F:Godot.RenderingServer.EnvironmentSsaoQuality.Ultra
  id: Ultra
  parent: Godot.RenderingServer.EnvironmentSsaoQuality
  langs:
  - csharp
  - vb
  name: Ultra
  nameWithType: RenderingServer.EnvironmentSsaoQuality.Ultra
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality.Ultra
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Ultra = 4
    return:
      type: Godot.RenderingServer.EnvironmentSsaoQuality
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSsaoQuality
  commentId: T:Godot.RenderingServer.EnvironmentSsaoQuality
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSsaoQuality
  nameWithType: RenderingServer.EnvironmentSsaoQuality
  fullName: Godot.RenderingServer.EnvironmentSsaoQuality
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSsaoQuality
    name: EnvironmentSsaoQuality
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSsaoQuality.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSsaoQuality
    name: EnvironmentSsaoQuality
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSsaoQuality.html
