### YamlMime:ManagedReference
items:
- uid: Godot.XRInterface.EnvironmentBlendModeEnum
  commentId: T:Godot.XRInterface.EnvironmentBlendModeEnum
  id: XRInterface.EnvironmentBlendModeEnum
  parent: Godot
  children:
  - Godot.XRInterface.EnvironmentBlendModeEnum.Additive
  - Godot.XRInterface.EnvironmentBlendModeEnum.AlphaBlend
  - Godot.XRInterface.EnvironmentBlendModeEnum.Opaque
  langs:
  - csharp
  - vb
  name: XRInterface.EnvironmentBlendModeEnum
  nameWithType: XRInterface.EnvironmentBlendModeEnum
  fullName: Godot.XRInterface.EnvironmentBlendModeEnum
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum XRInterface.EnvironmentBlendModeEnum : long'
    content.vb: Public Enum XRInterface.EnvironmentBlendModeEnum As Long
- uid: Godot.XRInterface.EnvironmentBlendModeEnum.Opaque
  commentId: F:Godot.XRInterface.EnvironmentBlendModeEnum.Opaque
  id: Opaque
  parent: Godot.XRInterface.EnvironmentBlendModeEnum
  langs:
  - csharp
  - vb
  name: Opaque
  nameWithType: XRInterface.EnvironmentBlendModeEnum.Opaque
  fullName: Godot.XRInterface.EnvironmentBlendModeEnum.Opaque
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Opaque = 0
    return:
      type: Godot.XRInterface.EnvironmentBlendModeEnum
- uid: Godot.XRInterface.EnvironmentBlendModeEnum.Additive
  commentId: F:Godot.XRInterface.EnvironmentBlendModeEnum.Additive
  id: Additive
  parent: Godot.XRInterface.EnvironmentBlendModeEnum
  langs:
  - csharp
  - vb
  name: Additive
  nameWithType: XRInterface.EnvironmentBlendModeEnum.Additive
  fullName: Godot.XRInterface.EnvironmentBlendModeEnum.Additive
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Additive = 1
    return:
      type: Godot.XRInterface.EnvironmentBlendModeEnum
- uid: Godot.XRInterface.EnvironmentBlendModeEnum.AlphaBlend
  commentId: F:Godot.XRInterface.EnvironmentBlendModeEnum.AlphaBlend
  id: AlphaBlend
  parent: Godot.XRInterface.EnvironmentBlendModeEnum
  langs:
  - csharp
  - vb
  name: AlphaBlend
  nameWithType: XRInterface.EnvironmentBlendModeEnum.AlphaBlend
  fullName: Godot.XRInterface.EnvironmentBlendModeEnum.AlphaBlend
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: AlphaBlend = 2
    return:
      type: Godot.XRInterface.EnvironmentBlendModeEnum
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.XRInterface.EnvironmentBlendModeEnum
  commentId: T:Godot.XRInterface.EnvironmentBlendModeEnum
  parent: Godot
  isExternal: true
  href: Godot.XRInterface.html
  name: XRInterface.EnvironmentBlendModeEnum
  nameWithType: XRInterface.EnvironmentBlendModeEnum
  fullName: Godot.XRInterface.EnvironmentBlendModeEnum
  spec.csharp:
  - uid: Godot.XRInterface
    name: XRInterface
    isExternal: true
    href: Godot.XRInterface.html
  - name: .
  - uid: Godot.XRInterface.EnvironmentBlendModeEnum
    name: EnvironmentBlendModeEnum
    isExternal: true
    href: Godot.XRInterface.EnvironmentBlendModeEnum.html
  spec.vb:
  - uid: Godot.XRInterface
    name: XRInterface
    isExternal: true
    href: Godot.XRInterface.html
  - name: .
  - uid: Godot.XRInterface.EnvironmentBlendModeEnum
    name: EnvironmentBlendModeEnum
    isExternal: true
    href: Godot.XRInterface.EnvironmentBlendModeEnum.html
