### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  id: RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In16Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In1Frame
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In2Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In4Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In8Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.Max
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSdfgiFramesToUpdateLight : long'
    content.vb: Public Enum RenderingServer.EnvironmentSdfgiFramesToUpdateLight As Long
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In1Frame
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In1Frame
  id: In1Frame
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: In1Frame
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In1Frame
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In1Frame
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In1Frame = 0
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In2Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In2Frames
  id: In2Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: In2Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In2Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In2Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In2Frames = 1
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In4Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In4Frames
  id: In4Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: In4Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In4Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In4Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In4Frames = 2
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In8Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In8Frames
  id: In8Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: In8Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In8Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In8Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In8Frames = 3
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In16Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In16Frames
  id: In16Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: In16Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In16Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.In16Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In16Frames = 4
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.Max
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.Max
  id: Max
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight.Max
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 5
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
    name: EnvironmentSdfgiFramesToUpdateLight
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight
    name: EnvironmentSdfgiFramesToUpdateLight
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiFramesToUpdateLight.html
