### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.ViewportEnvironmentMode
  commentId: T:Godot.RenderingServer.ViewportEnvironmentMode
  id: RenderingServer.ViewportEnvironmentMode
  parent: Godot
  children:
  - Godot.RenderingServer.ViewportEnvironmentMode.Disabled
  - Godot.RenderingServer.ViewportEnvironmentMode.Enabled
  - Godot.RenderingServer.ViewportEnvironmentMode.Inherit
  - Godot.RenderingServer.ViewportEnvironmentMode.Max
  langs:
  - csharp
  - vb
  name: RenderingServer.ViewportEnvironmentMode
  nameWithType: RenderingServer.ViewportEnvironmentMode
  fullName: Godot.RenderingServer.ViewportEnvironmentMode
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.ViewportEnvironmentMode : long'
    content.vb: Public Enum RenderingServer.ViewportEnvironmentMode As Long
- uid: Godot.RenderingServer.ViewportEnvironmentMode.Disabled
  commentId: F:Godot.RenderingServer.ViewportEnvironmentMode.Disabled
  id: Disabled
  parent: Godot.RenderingServer.ViewportEnvironmentMode
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RenderingServer.ViewportEnvironmentMode.Disabled
  fullName: Godot.RenderingServer.ViewportEnvironmentMode.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 0
    return:
      type: Godot.RenderingServer.ViewportEnvironmentMode
- uid: Godot.RenderingServer.ViewportEnvironmentMode.Enabled
  commentId: F:Godot.RenderingServer.ViewportEnvironmentMode.Enabled
  id: Enabled
  parent: Godot.RenderingServer.ViewportEnvironmentMode
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: RenderingServer.ViewportEnvironmentMode.Enabled
  fullName: Godot.RenderingServer.ViewportEnvironmentMode.Enabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Enabled = 1
    return:
      type: Godot.RenderingServer.ViewportEnvironmentMode
- uid: Godot.RenderingServer.ViewportEnvironmentMode.Inherit
  commentId: F:Godot.RenderingServer.ViewportEnvironmentMode.Inherit
  id: Inherit
  parent: Godot.RenderingServer.ViewportEnvironmentMode
  langs:
  - csharp
  - vb
  name: Inherit
  nameWithType: RenderingServer.ViewportEnvironmentMode.Inherit
  fullName: Godot.RenderingServer.ViewportEnvironmentMode.Inherit
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Inherit = 2
    return:
      type: Godot.RenderingServer.ViewportEnvironmentMode
- uid: Godot.RenderingServer.ViewportEnvironmentMode.Max
  commentId: F:Godot.RenderingServer.ViewportEnvironmentMode.Max
  id: Max
  parent: Godot.RenderingServer.ViewportEnvironmentMode
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: RenderingServer.ViewportEnvironmentMode.Max
  fullName: Godot.RenderingServer.ViewportEnvironmentMode.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 3
    return:
      type: Godot.RenderingServer.ViewportEnvironmentMode
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.ViewportEnvironmentMode
  commentId: T:Godot.RenderingServer.ViewportEnvironmentMode
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.ViewportEnvironmentMode
  nameWithType: RenderingServer.ViewportEnvironmentMode
  fullName: Godot.RenderingServer.ViewportEnvironmentMode
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.ViewportEnvironmentMode
    name: ViewportEnvironmentMode
    isExternal: true
    href: Godot.RenderingServer.ViewportEnvironmentMode.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.ViewportEnvironmentMode
    name: ViewportEnvironmentMode
    isExternal: true
    href: Godot.RenderingServer.ViewportEnvironmentMode.html
