### YamlMime:ManagedReference
items:
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName
  commentId: T:Godot.RenderSceneBuffersConfiguration.PropertyName
  id: RenderSceneBuffersConfiguration.PropertyName
  parent: Godot
  children:
  - Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor
  - Godot.RenderSceneBuffersConfiguration.PropertyName.AnisotropicFilteringLevel
  - Godot.RenderSceneBuffersConfiguration.PropertyName.FsrSharpness
  - Godot.RenderSceneBuffersConfiguration.PropertyName.InternalSize
  - Godot.RenderSceneBuffersConfiguration.PropertyName.Msaa3D
  - Godot.RenderSceneBuffersConfiguration.PropertyName.RenderTarget
  - Godot.RenderSceneBuffersConfiguration.PropertyName.Scaling3DMode
  - Godot.RenderSceneBuffersConfiguration.PropertyName.ScreenSpaceAA
  - Godot.RenderSceneBuffersConfiguration.PropertyName.TargetSize
  - Godot.RenderSceneBuffersConfiguration.PropertyName.TextureMipmapBias
  - Godot.RenderSceneBuffersConfiguration.PropertyName.ViewCount
  langs:
  - csharp
  - vb
  name: RenderSceneBuffersConfiguration.PropertyName
  nameWithType: RenderSceneBuffersConfiguration.PropertyName
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName
  type: Class
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public class RenderSceneBuffersConfiguration.PropertyName : RefCounted.PropertyName'
    content.vb: Public Class RenderSceneBuffersConfiguration.PropertyName Inherits RefCounted.PropertyName
  inheritance:
  - System.Object
  - Godot.GodotObject.PropertyName
  - Godot.RefCounted.PropertyName
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.RenderTarget
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.RenderTarget
  id: RenderTarget
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: RenderTarget
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.RenderTarget
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.RenderTarget
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName RenderTarget
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly RenderTarget As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.InternalSize
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.InternalSize
  id: InternalSize
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: InternalSize
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.InternalSize
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.InternalSize
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName InternalSize
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly InternalSize As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.TargetSize
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.TargetSize
  id: TargetSize
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: TargetSize
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.TargetSize
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.TargetSize
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName TargetSize
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly TargetSize As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.ViewCount
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.ViewCount
  id: ViewCount
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: ViewCount
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.ViewCount
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.ViewCount
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName ViewCount
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly ViewCount As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.Scaling3DMode
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.Scaling3DMode
  id: Scaling3DMode
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: Scaling3DMode
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.Scaling3DMode
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.Scaling3DMode
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName Scaling3DMode
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly Scaling3DMode As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.Msaa3D
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.Msaa3D
  id: Msaa3D
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: Msaa3D
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.Msaa3D
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.Msaa3D
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName Msaa3D
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly Msaa3D As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.ScreenSpaceAA
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.ScreenSpaceAA
  id: ScreenSpaceAA
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: ScreenSpaceAA
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.ScreenSpaceAA
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.ScreenSpaceAA
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName ScreenSpaceAA
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly ScreenSpaceAA As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.FsrSharpness
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.FsrSharpness
  id: FsrSharpness
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: FsrSharpness
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.FsrSharpness
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.FsrSharpness
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName FsrSharpness
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly FsrSharpness As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.TextureMipmapBias
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.TextureMipmapBias
  id: TextureMipmapBias
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: TextureMipmapBias
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.TextureMipmapBias
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.TextureMipmapBias
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName TextureMipmapBias
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly TextureMipmapBias As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.AnisotropicFilteringLevel
  commentId: F:Godot.RenderSceneBuffersConfiguration.PropertyName.AnisotropicFilteringLevel
  id: AnisotropicFilteringLevel
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: AnisotropicFilteringLevel
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.AnisotropicFilteringLevel
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.AnisotropicFilteringLevel
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public static readonly StringName AnisotropicFilteringLevel
    return:
      type: Godot.StringName
    content.vb: Public Shared ReadOnly AnisotropicFilteringLevel As StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor
  commentId: M:Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor
  id: '#ctor'
  parent: Godot.RenderSceneBuffersConfiguration.PropertyName
  langs:
  - csharp
  - vb
  name: PropertyName()
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.PropertyName()
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.PropertyName()
  type: Constructor
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public PropertyName()
    content.vb: Public Sub New()
  overload: Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor*
  nameWithType.vb: RenderSceneBuffersConfiguration.PropertyName.New()
  fullName.vb: Godot.RenderSceneBuffersConfiguration.PropertyName.New()
  name.vb: New()
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Godot.GodotObject.PropertyName
  commentId: T:Godot.GodotObject.PropertyName
  parent: Godot
  isExternal: true
  href: Godot.GodotObject.html
  name: GodotObject.PropertyName
  nameWithType: GodotObject.PropertyName
  fullName: Godot.GodotObject.PropertyName
  spec.csharp:
  - uid: Godot.GodotObject
    name: GodotObject
    isExternal: true
    href: Godot.GodotObject.html
  - name: .
  - uid: Godot.GodotObject.PropertyName
    name: PropertyName
    isExternal: true
    href: Godot.GodotObject.PropertyName.html
  spec.vb:
  - uid: Godot.GodotObject
    name: GodotObject
    isExternal: true
    href: Godot.GodotObject.html
  - name: .
  - uid: Godot.GodotObject.PropertyName
    name: PropertyName
    isExternal: true
    href: Godot.GodotObject.PropertyName.html
- uid: Godot.RefCounted.PropertyName
  commentId: T:Godot.RefCounted.PropertyName
  parent: Godot
  isExternal: true
  href: Godot.RefCounted.html
  name: RefCounted.PropertyName
  nameWithType: RefCounted.PropertyName
  fullName: Godot.RefCounted.PropertyName
  spec.csharp:
  - uid: Godot.RefCounted
    name: RefCounted
    isExternal: true
    href: Godot.RefCounted.html
  - name: .
  - uid: Godot.RefCounted.PropertyName
    name: PropertyName
    isExternal: true
    href: Godot.RefCounted.PropertyName.html
  spec.vb:
  - uid: Godot.RefCounted
    name: RefCounted
    isExternal: true
    href: Godot.RefCounted.html
  - name: .
  - uid: Godot.RefCounted.PropertyName
    name: PropertyName
    isExternal: true
    href: Godot.RefCounted.PropertyName.html
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Godot.StringName
  commentId: T:Godot.StringName
  parent: Godot
  isExternal: true
  href: Godot.StringName.html
  name: StringName
  nameWithType: StringName
  fullName: Godot.StringName
- uid: Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor*
  commentId: Overload:Godot.RenderSceneBuffersConfiguration.PropertyName.#ctor
  isExternal: true
  href: Godot.RenderSceneBuffersConfiguration.PropertyName.html#Godot_RenderSceneBuffersConfiguration_PropertyName__ctor
  name: PropertyName
  nameWithType: RenderSceneBuffersConfiguration.PropertyName.PropertyName
  fullName: Godot.RenderSceneBuffersConfiguration.PropertyName.PropertyName
  nameWithType.vb: RenderSceneBuffersConfiguration.PropertyName.New
  fullName.vb: Godot.RenderSceneBuffersConfiguration.PropertyName.New
  name.vb: New
