### YamlMime:ManagedReference
items:
- uid: Godot.Environment.ReflectionSource
  commentId: T:Godot.Environment.ReflectionSource
  id: Environment.ReflectionSource
  parent: Godot
  children:
  - Godot.Environment.ReflectionSource.Bg
  - Godot.Environment.ReflectionSource.Disabled
  - Godot.Environment.ReflectionSource.Sky
  langs:
  - csharp
  - vb
  name: Environment.ReflectionSource
  nameWithType: Environment.ReflectionSource
  fullName: Godot.Environment.ReflectionSource
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.ReflectionSource : long'
    content.vb: Public Enum Environment.ReflectionSource As Long
- uid: Godot.Environment.ReflectionSource.Bg
  commentId: F:Godot.Environment.ReflectionSource.Bg
  id: Bg
  parent: Godot.Environment.ReflectionSource
  langs:
  - csharp
  - vb
  name: Bg
  nameWithType: Environment.ReflectionSource.Bg
  fullName: Godot.Environment.ReflectionSource.Bg
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Bg = 0
    return:
      type: Godot.Environment.ReflectionSource
- uid: Godot.Environment.ReflectionSource.Disabled
  commentId: F:Godot.Environment.ReflectionSource.Disabled
  id: Disabled
  parent: Godot.Environment.ReflectionSource
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: Environment.ReflectionSource.Disabled
  fullName: Godot.Environment.ReflectionSource.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 1
    return:
      type: Godot.Environment.ReflectionSource
- uid: Godot.Environment.ReflectionSource.Sky
  commentId: F:Godot.Environment.ReflectionSource.Sky
  id: Sky
  parent: Godot.Environment.ReflectionSource
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: Environment.ReflectionSource.Sky
  fullName: Godot.Environment.ReflectionSource.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 2
    return:
      type: Godot.Environment.ReflectionSource
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.ReflectionSource
  commentId: T:Godot.Environment.ReflectionSource
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.ReflectionSource
  nameWithType: Environment.ReflectionSource
  fullName: Godot.Environment.ReflectionSource
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.ReflectionSource
    name: ReflectionSource
    isExternal: true
    href: Godot.Environment.ReflectionSource.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.ReflectionSource
    name: ReflectionSource
    isExternal: true
    href: Godot.Environment.ReflectionSource.html
