### YamlMime:ManagedReference
items:
- uid: Godot.MeshConvexDecompositionSettings.ModeEnum
  commentId: T:Godot.MeshConvexDecompositionSettings.ModeEnum
  id: MeshConvexDecompositionSettings.ModeEnum
  parent: Godot
  children:
  - Godot.MeshConvexDecompositionSettings.ModeEnum.Tetrahedron
  - Godot.MeshConvexDecompositionSettings.ModeEnum.Voxel
  langs:
  - csharp
  - vb
  name: MeshConvexDecompositionSettings.ModeEnum
  nameWithType: MeshConvexDecompositionSettings.ModeEnum
  fullName: Godot.MeshConvexDecompositionSettings.ModeEnum
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum MeshConvexDecompositionSettings.ModeEnum : long'
    content.vb: Public Enum MeshConvexDecompositionSettings.ModeEnum As Long
- uid: Godot.MeshConvexDecompositionSettings.ModeEnum.Voxel
  commentId: F:Godot.MeshConvexDecompositionSettings.ModeEnum.Voxel
  id: Voxel
  parent: Godot.MeshConvexDecompositionSettings.ModeEnum
  langs:
  - csharp
  - vb
  name: Voxel
  nameWithType: MeshConvexDecompositionSettings.ModeEnum.Voxel
  fullName: Godot.MeshConvexDecompositionSettings.ModeEnum.Voxel
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Voxel = 0
    return:
      type: Godot.MeshConvexDecompositionSettings.ModeEnum
- uid: Godot.MeshConvexDecompositionSettings.ModeEnum.Tetrahedron
  commentId: F:Godot.MeshConvexDecompositionSettings.ModeEnum.Tetrahedron
  id: Tetrahedron
  parent: Godot.MeshConvexDecompositionSettings.ModeEnum
  langs:
  - csharp
  - vb
  name: Tetrahedron
  nameWithType: MeshConvexDecompositionSettings.ModeEnum.Tetrahedron
  fullName: Godot.MeshConvexDecompositionSettings.ModeEnum.Tetrahedron
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Tetrahedron = 1
    return:
      type: Godot.MeshConvexDecompositionSettings.ModeEnum
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.MeshConvexDecompositionSettings.ModeEnum
  commentId: T:Godot.MeshConvexDecompositionSettings.ModeEnum
  parent: Godot
  isExternal: true
  href: Godot.MeshConvexDecompositionSettings.html
  name: MeshConvexDecompositionSettings.ModeEnum
  nameWithType: MeshConvexDecompositionSettings.ModeEnum
  fullName: Godot.MeshConvexDecompositionSettings.ModeEnum
  spec.csharp:
  - uid: Godot.MeshConvexDecompositionSettings
    name: MeshConvexDecompositionSettings
    isExternal: true
    href: Godot.MeshConvexDecompositionSettings.html
  - name: .
  - uid: Godot.MeshConvexDecompositionSettings.ModeEnum
    name: ModeEnum
    isExternal: true
    href: Godot.MeshConvexDecompositionSettings.ModeEnum.html
  spec.vb:
  - uid: Godot.MeshConvexDecompositionSettings
    name: MeshConvexDecompositionSettings
    isExternal: true
    href: Godot.MeshConvexDecompositionSettings.html
  - name: .
  - uid: Godot.MeshConvexDecompositionSettings.ModeEnum
    name: ModeEnum
    isExternal: true
    href: Godot.MeshConvexDecompositionSettings.ModeEnum.html
