### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentBG
  commentId: T:Godot.RenderingServer.EnvironmentBG
  id: RenderingServer.EnvironmentBG
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentBG.CameraFeed
  - Godot.RenderingServer.EnvironmentBG.Canvas
  - Godot.RenderingServer.EnvironmentBG.ClearColor
  - Godot.RenderingServer.EnvironmentBG.Color
  - Godot.RenderingServer.EnvironmentBG.Keep
  - Godot.RenderingServer.EnvironmentBG.Max
  - Godot.RenderingServer.EnvironmentBG.Sky
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentBG
  nameWithType: RenderingServer.EnvironmentBG
  fullName: Godot.RenderingServer.EnvironmentBG
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentBG : long'
    content.vb: Public Enum RenderingServer.EnvironmentBG As Long
- uid: Godot.RenderingServer.EnvironmentBG.ClearColor
  commentId: F:Godot.RenderingServer.EnvironmentBG.ClearColor
  id: ClearColor
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: ClearColor
  nameWithType: RenderingServer.EnvironmentBG.ClearColor
  fullName: Godot.RenderingServer.EnvironmentBG.ClearColor
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: ClearColor = 0
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.Color
  commentId: F:Godot.RenderingServer.EnvironmentBG.Color
  id: Color
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: RenderingServer.EnvironmentBG.Color
  fullName: Godot.RenderingServer.EnvironmentBG.Color
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Color = 1
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.Sky
  commentId: F:Godot.RenderingServer.EnvironmentBG.Sky
  id: Sky
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: RenderingServer.EnvironmentBG.Sky
  fullName: Godot.RenderingServer.EnvironmentBG.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 2
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.Canvas
  commentId: F:Godot.RenderingServer.EnvironmentBG.Canvas
  id: Canvas
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: Canvas
  nameWithType: RenderingServer.EnvironmentBG.Canvas
  fullName: Godot.RenderingServer.EnvironmentBG.Canvas
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Canvas = 3
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.Keep
  commentId: F:Godot.RenderingServer.EnvironmentBG.Keep
  id: Keep
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: Keep
  nameWithType: RenderingServer.EnvironmentBG.Keep
  fullName: Godot.RenderingServer.EnvironmentBG.Keep
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Keep = 4
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.CameraFeed
  commentId: F:Godot.RenderingServer.EnvironmentBG.CameraFeed
  id: CameraFeed
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: CameraFeed
  nameWithType: RenderingServer.EnvironmentBG.CameraFeed
  fullName: Godot.RenderingServer.EnvironmentBG.CameraFeed
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: CameraFeed = 5
    return:
      type: Godot.RenderingServer.EnvironmentBG
- uid: Godot.RenderingServer.EnvironmentBG.Max
  commentId: F:Godot.RenderingServer.EnvironmentBG.Max
  id: Max
  parent: Godot.RenderingServer.EnvironmentBG
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: RenderingServer.EnvironmentBG.Max
  fullName: Godot.RenderingServer.EnvironmentBG.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 6
    return:
      type: Godot.RenderingServer.EnvironmentBG
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentBG
  commentId: T:Godot.RenderingServer.EnvironmentBG
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentBG
  nameWithType: RenderingServer.EnvironmentBG
  fullName: Godot.RenderingServer.EnvironmentBG
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentBG
    name: EnvironmentBG
    isExternal: true
    href: Godot.RenderingServer.EnvironmentBG.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentBG
    name: EnvironmentBG
    isExternal: true
    href: Godot.RenderingServer.EnvironmentBG.html
