### YamlMime:ManagedReference
items:
- uid: Godot.Environment.BGMode
  commentId: T:Godot.Environment.BGMode
  id: Environment.BGMode
  parent: Godot
  children:
  - Godot.Environment.BGMode.CameraFeed
  - Godot.Environment.BGMode.Canvas
  - Godot.Environment.BGMode.ClearColor
  - Godot.Environment.BGMode.Color
  - Godot.Environment.BGMode.Keep
  - Godot.Environment.BGMode.Max
  - Godot.Environment.BGMode.Sky
  langs:
  - csharp
  - vb
  name: Environment.BGMode
  nameWithType: Environment.BGMode
  fullName: Godot.Environment.BGMode
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.BGMode : long'
    content.vb: Public Enum Environment.BGMode As Long
- uid: Godot.Environment.BGMode.ClearColor
  commentId: F:Godot.Environment.BGMode.ClearColor
  id: ClearColor
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: ClearColor
  nameWithType: Environment.BGMode.ClearColor
  fullName: Godot.Environment.BGMode.ClearColor
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: ClearColor = 0
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.Color
  commentId: F:Godot.Environment.BGMode.Color
  id: Color
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: Environment.BGMode.Color
  fullName: Godot.Environment.BGMode.Color
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Color = 1
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.Sky
  commentId: F:Godot.Environment.BGMode.Sky
  id: Sky
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: Environment.BGMode.Sky
  fullName: Godot.Environment.BGMode.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 2
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.Canvas
  commentId: F:Godot.Environment.BGMode.Canvas
  id: Canvas
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: Canvas
  nameWithType: Environment.BGMode.Canvas
  fullName: Godot.Environment.BGMode.Canvas
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Canvas = 3
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.Keep
  commentId: F:Godot.Environment.BGMode.Keep
  id: Keep
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: Keep
  nameWithType: Environment.BGMode.Keep
  fullName: Godot.Environment.BGMode.Keep
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Keep = 4
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.CameraFeed
  commentId: F:Godot.Environment.BGMode.CameraFeed
  id: CameraFeed
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: CameraFeed
  nameWithType: Environment.BGMode.CameraFeed
  fullName: Godot.Environment.BGMode.CameraFeed
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: CameraFeed = 5
    return:
      type: Godot.Environment.BGMode
- uid: Godot.Environment.BGMode.Max
  commentId: F:Godot.Environment.BGMode.Max
  id: Max
  parent: Godot.Environment.BGMode
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: Environment.BGMode.Max
  fullName: Godot.Environment.BGMode.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 6
    return:
      type: Godot.Environment.BGMode
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.BGMode
  commentId: T:Godot.Environment.BGMode
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.BGMode
  nameWithType: Environment.BGMode
  fullName: Godot.Environment.BGMode
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.BGMode
    name: BGMode
    isExternal: true
    href: Godot.Environment.BGMode.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.BGMode
    name: BGMode
    isExternal: true
    href: Godot.Environment.BGMode.html
