### YamlMime:ManagedReference
items:
- uid: Godot.LightmapGI.EnvironmentModeEnum
  commentId: T:Godot.LightmapGI.EnvironmentModeEnum
  id: LightmapGI.EnvironmentModeEnum
  parent: Godot
  children:
  - Godot.LightmapGI.EnvironmentModeEnum.CustomColor
  - Godot.LightmapGI.EnvironmentModeEnum.CustomSky
  - Godot.LightmapGI.EnvironmentModeEnum.Disabled
  - Godot.LightmapGI.EnvironmentModeEnum.Scene
  langs:
  - csharp
  - vb
  name: LightmapGI.EnvironmentModeEnum
  nameWithType: LightmapGI.EnvironmentModeEnum
  fullName: Godot.LightmapGI.EnvironmentModeEnum
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum LightmapGI.EnvironmentModeEnum : long'
    content.vb: Public Enum LightmapGI.EnvironmentModeEnum As Long
- uid: Godot.LightmapGI.EnvironmentModeEnum.Disabled
  commentId: F:Godot.LightmapGI.EnvironmentModeEnum.Disabled
  id: Disabled
  parent: Godot.LightmapGI.EnvironmentModeEnum
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: LightmapGI.EnvironmentModeEnum.Disabled
  fullName: Godot.LightmapGI.EnvironmentModeEnum.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 0
    return:
      type: Godot.LightmapGI.EnvironmentModeEnum
- uid: Godot.LightmapGI.EnvironmentModeEnum.Scene
  commentId: F:Godot.LightmapGI.EnvironmentModeEnum.Scene
  id: Scene
  parent: Godot.LightmapGI.EnvironmentModeEnum
  langs:
  - csharp
  - vb
  name: Scene
  nameWithType: LightmapGI.EnvironmentModeEnum.Scene
  fullName: Godot.LightmapGI.EnvironmentModeEnum.Scene
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scene = 1
    return:
      type: Godot.LightmapGI.EnvironmentModeEnum
- uid: Godot.LightmapGI.EnvironmentModeEnum.CustomSky
  commentId: F:Godot.LightmapGI.EnvironmentModeEnum.CustomSky
  id: CustomSky
  parent: Godot.LightmapGI.EnvironmentModeEnum
  langs:
  - csharp
  - vb
  name: CustomSky
  nameWithType: LightmapGI.EnvironmentModeEnum.CustomSky
  fullName: Godot.LightmapGI.EnvironmentModeEnum.CustomSky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: CustomSky = 2
    return:
      type: Godot.LightmapGI.EnvironmentModeEnum
- uid: Godot.LightmapGI.EnvironmentModeEnum.CustomColor
  commentId: F:Godot.LightmapGI.EnvironmentModeEnum.CustomColor
  id: CustomColor
  parent: Godot.LightmapGI.EnvironmentModeEnum
  langs:
  - csharp
  - vb
  name: CustomColor
  nameWithType: LightmapGI.EnvironmentModeEnum.CustomColor
  fullName: Godot.LightmapGI.EnvironmentModeEnum.CustomColor
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: CustomColor = 3
    return:
      type: Godot.LightmapGI.EnvironmentModeEnum
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.LightmapGI.EnvironmentModeEnum
  commentId: T:Godot.LightmapGI.EnvironmentModeEnum
  parent: Godot
  isExternal: true
  href: Godot.LightmapGI.html
  name: LightmapGI.EnvironmentModeEnum
  nameWithType: LightmapGI.EnvironmentModeEnum
  fullName: Godot.LightmapGI.EnvironmentModeEnum
  spec.csharp:
  - uid: Godot.LightmapGI
    name: LightmapGI
    isExternal: true
    href: Godot.LightmapGI.html
  - name: .
  - uid: Godot.LightmapGI.EnvironmentModeEnum
    name: EnvironmentModeEnum
    isExternal: true
    href: Godot.LightmapGI.EnvironmentModeEnum.html
  spec.vb:
  - uid: Godot.LightmapGI
    name: LightmapGI
    isExternal: true
    href: Godot.LightmapGI.html
  - name: .
  - uid: Godot.LightmapGI.EnvironmentModeEnum
    name: EnvironmentModeEnum
    isExternal: true
    href: Godot.LightmapGI.EnvironmentModeEnum.html
