### YamlMime:ManagedReference
items:
- uid: Godot.SceneReplicationConfig.ReplicationMode
  commentId: T:Godot.SceneReplicationConfig.ReplicationMode
  id: SceneReplicationConfig.ReplicationMode
  parent: Godot
  children:
  - Godot.SceneReplicationConfig.ReplicationMode.Always
  - Godot.SceneReplicationConfig.ReplicationMode.Never
  - Godot.SceneReplicationConfig.ReplicationMode.OnChange
  langs:
  - csharp
  - vb
  name: SceneReplicationConfig.ReplicationMode
  nameWithType: SceneReplicationConfig.ReplicationMode
  fullName: Godot.SceneReplicationConfig.ReplicationMode
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum SceneReplicationConfig.ReplicationMode : long'
    content.vb: Public Enum SceneReplicationConfig.ReplicationMode As Long
- uid: Godot.SceneReplicationConfig.ReplicationMode.Never
  commentId: F:Godot.SceneReplicationConfig.ReplicationMode.Never
  id: Never
  parent: Godot.SceneReplicationConfig.ReplicationMode
  langs:
  - csharp
  - vb
  name: Never
  nameWithType: SceneReplicationConfig.ReplicationMode.Never
  fullName: Godot.SceneReplicationConfig.ReplicationMode.Never
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Never = 0
    return:
      type: Godot.SceneReplicationConfig.ReplicationMode
- uid: Godot.SceneReplicationConfig.ReplicationMode.Always
  commentId: F:Godot.SceneReplicationConfig.ReplicationMode.Always
  id: Always
  parent: Godot.SceneReplicationConfig.ReplicationMode
  langs:
  - csharp
  - vb
  name: Always
  nameWithType: SceneReplicationConfig.ReplicationMode.Always
  fullName: Godot.SceneReplicationConfig.ReplicationMode.Always
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Always = 1
    return:
      type: Godot.SceneReplicationConfig.ReplicationMode
- uid: Godot.SceneReplicationConfig.ReplicationMode.OnChange
  commentId: F:Godot.SceneReplicationConfig.ReplicationMode.OnChange
  id: OnChange
  parent: Godot.SceneReplicationConfig.ReplicationMode
  langs:
  - csharp
  - vb
  name: OnChange
  nameWithType: SceneReplicationConfig.ReplicationMode.OnChange
  fullName: Godot.SceneReplicationConfig.ReplicationMode.OnChange
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: OnChange = 2
    return:
      type: Godot.SceneReplicationConfig.ReplicationMode
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.SceneReplicationConfig.ReplicationMode
  commentId: T:Godot.SceneReplicationConfig.ReplicationMode
  parent: Godot
  isExternal: true
  href: Godot.SceneReplicationConfig.html
  name: SceneReplicationConfig.ReplicationMode
  nameWithType: SceneReplicationConfig.ReplicationMode
  fullName: Godot.SceneReplicationConfig.ReplicationMode
  spec.csharp:
  - uid: Godot.SceneReplicationConfig
    name: SceneReplicationConfig
    isExternal: true
    href: Godot.SceneReplicationConfig.html
  - name: .
  - uid: Godot.SceneReplicationConfig.ReplicationMode
    name: ReplicationMode
    isExternal: true
    href: Godot.SceneReplicationConfig.ReplicationMode.html
  spec.vb:
  - uid: Godot.SceneReplicationConfig
    name: SceneReplicationConfig
    isExternal: true
    href: Godot.SceneReplicationConfig.html
  - name: .
  - uid: Godot.SceneReplicationConfig.ReplicationMode
    name: ReplicationMode
    isExternal: true
    href: Godot.SceneReplicationConfig.ReplicationMode.html
