### YamlMime:ManagedReference
items:
- uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  commentId: T:Godot.OpenXRInterface.PerfSettingsNotificationLevel
  id: OpenXRInterface.PerfSettingsNotificationLevel
  parent: Godot
  children:
  - Godot.OpenXRInterface.PerfSettingsNotificationLevel.Impaired
  - Godot.OpenXRInterface.PerfSettingsNotificationLevel.Normal
  - Godot.OpenXRInterface.PerfSettingsNotificationLevel.Warning
  langs:
  - csharp
  - vb
  name: OpenXRInterface.PerfSettingsNotificationLevel
  nameWithType: OpenXRInterface.PerfSettingsNotificationLevel
  fullName: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum OpenXRInterface.PerfSettingsNotificationLevel : long'
    content.vb: Public Enum OpenXRInterface.PerfSettingsNotificationLevel As Long
- uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Normal
  commentId: F:Godot.OpenXRInterface.PerfSettingsNotificationLevel.Normal
  id: Normal
  parent: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  langs:
  - csharp
  - vb
  name: Normal
  nameWithType: OpenXRInterface.PerfSettingsNotificationLevel.Normal
  fullName: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Normal
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Normal = 0
    return:
      type: Godot.OpenXRInterface.PerfSettingsNotificationLevel
- uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Warning
  commentId: F:Godot.OpenXRInterface.PerfSettingsNotificationLevel.Warning
  id: Warning
  parent: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  langs:
  - csharp
  - vb
  name: Warning
  nameWithType: OpenXRInterface.PerfSettingsNotificationLevel.Warning
  fullName: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Warning
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Warning = 1
    return:
      type: Godot.OpenXRInterface.PerfSettingsNotificationLevel
- uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Impaired
  commentId: F:Godot.OpenXRInterface.PerfSettingsNotificationLevel.Impaired
  id: Impaired
  parent: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  langs:
  - csharp
  - vb
  name: Impaired
  nameWithType: OpenXRInterface.PerfSettingsNotificationLevel.Impaired
  fullName: Godot.OpenXRInterface.PerfSettingsNotificationLevel.Impaired
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Impaired = 2
    return:
      type: Godot.OpenXRInterface.PerfSettingsNotificationLevel
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  commentId: T:Godot.OpenXRInterface.PerfSettingsNotificationLevel
  parent: Godot
  isExternal: true
  href: Godot.OpenXRInterface.html
  name: OpenXRInterface.PerfSettingsNotificationLevel
  nameWithType: OpenXRInterface.PerfSettingsNotificationLevel
  fullName: Godot.OpenXRInterface.PerfSettingsNotificationLevel
  spec.csharp:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel
    name: PerfSettingsNotificationLevel
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsNotificationLevel.html
  spec.vb:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsNotificationLevel
    name: PerfSettingsNotificationLevel
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsNotificationLevel.html
