### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  id: RenderingServer.EnvironmentSdfgiFramesToConverge
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In10Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In15Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In20Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In25Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In30Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In5Frames
  - Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.Max
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSdfgiFramesToConverge
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSdfgiFramesToConverge : long'
    content.vb: Public Enum RenderingServer.EnvironmentSdfgiFramesToConverge As Long
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In5Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In5Frames
  id: In5Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In5Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In5Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In5Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In5Frames = 0
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In10Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In10Frames
  id: In10Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In10Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In10Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In10Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In10Frames = 1
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In15Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In15Frames
  id: In15Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In15Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In15Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In15Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In15Frames = 2
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In20Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In20Frames
  id: In20Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In20Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In20Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In20Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In20Frames = 3
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In25Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In25Frames
  id: In25Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In25Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In25Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In25Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In25Frames = 4
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In30Frames
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In30Frames
  id: In30Frames
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: In30Frames
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.In30Frames
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.In30Frames
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: In30Frames = 5
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.Max
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.Max
  id: Max
  parent: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge.Max
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 6
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSdfgiFramesToConverge
  nameWithType: RenderingServer.EnvironmentSdfgiFramesToConverge
  fullName: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
    name: EnvironmentSdfgiFramesToConverge
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge
    name: EnvironmentSdfgiFramesToConverge
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiFramesToConverge.html
