### YamlMime:ManagedReference
items:
- uid: Godot.Environment.GlowBlendModeEnum
  commentId: T:Godot.Environment.GlowBlendModeEnum
  id: Environment.GlowBlendModeEnum
  parent: Godot
  children:
  - Godot.Environment.GlowBlendModeEnum.Additive
  - Godot.Environment.GlowBlendModeEnum.Mix
  - Godot.Environment.GlowBlendModeEnum.Replace
  - Godot.Environment.GlowBlendModeEnum.Screen
  - Godot.Environment.GlowBlendModeEnum.Softlight
  langs:
  - csharp
  - vb
  name: Environment.GlowBlendModeEnum
  nameWithType: Environment.GlowBlendModeEnum
  fullName: Godot.Environment.GlowBlendModeEnum
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.GlowBlendModeEnum : long'
    content.vb: Public Enum Environment.GlowBlendModeEnum As Long
- uid: Godot.Environment.GlowBlendModeEnum.Additive
  commentId: F:Godot.Environment.GlowBlendModeEnum.Additive
  id: Additive
  parent: Godot.Environment.GlowBlendModeEnum
  langs:
  - csharp
  - vb
  name: Additive
  nameWithType: Environment.GlowBlendModeEnum.Additive
  fullName: Godot.Environment.GlowBlendModeEnum.Additive
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Additive = 0
    return:
      type: Godot.Environment.GlowBlendModeEnum
- uid: Godot.Environment.GlowBlendModeEnum.Screen
  commentId: F:Godot.Environment.GlowBlendModeEnum.Screen
  id: Screen
  parent: Godot.Environment.GlowBlendModeEnum
  langs:
  - csharp
  - vb
  name: Screen
  nameWithType: Environment.GlowBlendModeEnum.Screen
  fullName: Godot.Environment.GlowBlendModeEnum.Screen
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Screen = 1
    return:
      type: Godot.Environment.GlowBlendModeEnum
- uid: Godot.Environment.GlowBlendModeEnum.Softlight
  commentId: F:Godot.Environment.GlowBlendModeEnum.Softlight
  id: Softlight
  parent: Godot.Environment.GlowBlendModeEnum
  langs:
  - csharp
  - vb
  name: Softlight
  nameWithType: Environment.GlowBlendModeEnum.Softlight
  fullName: Godot.Environment.GlowBlendModeEnum.Softlight
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Softlight = 2
    return:
      type: Godot.Environment.GlowBlendModeEnum
- uid: Godot.Environment.GlowBlendModeEnum.Replace
  commentId: F:Godot.Environment.GlowBlendModeEnum.Replace
  id: Replace
  parent: Godot.Environment.GlowBlendModeEnum
  langs:
  - csharp
  - vb
  name: Replace
  nameWithType: Environment.GlowBlendModeEnum.Replace
  fullName: Godot.Environment.GlowBlendModeEnum.Replace
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Replace = 3
    return:
      type: Godot.Environment.GlowBlendModeEnum
- uid: Godot.Environment.GlowBlendModeEnum.Mix
  commentId: F:Godot.Environment.GlowBlendModeEnum.Mix
  id: Mix
  parent: Godot.Environment.GlowBlendModeEnum
  langs:
  - csharp
  - vb
  name: Mix
  nameWithType: Environment.GlowBlendModeEnum.Mix
  fullName: Godot.Environment.GlowBlendModeEnum.Mix
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Mix = 4
    return:
      type: Godot.Environment.GlowBlendModeEnum
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.GlowBlendModeEnum
  commentId: T:Godot.Environment.GlowBlendModeEnum
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.GlowBlendModeEnum
  nameWithType: Environment.GlowBlendModeEnum
  fullName: Godot.Environment.GlowBlendModeEnum
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.GlowBlendModeEnum
    name: GlowBlendModeEnum
    isExternal: true
    href: Godot.Environment.GlowBlendModeEnum.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.GlowBlendModeEnum
    name: GlowBlendModeEnum
    isExternal: true
    href: Godot.Environment.GlowBlendModeEnum.html
