### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  commentId: T:Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  id: RenderingServer.EnvironmentSsrRoughnessQuality
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Disabled
  - Godot.RenderingServer.EnvironmentSsrRoughnessQuality.High
  - Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Low
  - Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Medium
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSsrRoughnessQuality
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSsrRoughnessQuality : long'
    content.vb: Public Enum RenderingServer.EnvironmentSsrRoughnessQuality As Long
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Disabled
  commentId: F:Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Disabled
  id: Disabled
  parent: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality.Disabled
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 0
    return:
      type: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Low
  commentId: F:Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Low
  id: Low
  parent: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  langs:
  - csharp
  - vb
  name: Low
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality.Low
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Low
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Low = 1
    return:
      type: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Medium
  commentId: F:Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Medium
  id: Medium
  parent: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  langs:
  - csharp
  - vb
  name: Medium
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality.Medium
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.Medium
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Medium = 2
    return:
      type: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.High
  commentId: F:Godot.RenderingServer.EnvironmentSsrRoughnessQuality.High
  id: High
  parent: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  langs:
  - csharp
  - vb
  name: High
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality.High
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.High
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: High = 3
    return:
      type: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  commentId: T:Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSsrRoughnessQuality
  nameWithType: RenderingServer.EnvironmentSsrRoughnessQuality
  fullName: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
    name: EnvironmentSsrRoughnessQuality
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSsrRoughnessQuality
    name: EnvironmentSsrRoughnessQuality
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSsrRoughnessQuality.html
