### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentToneMapper
  commentId: T:Godot.RenderingServer.EnvironmentToneMapper
  id: RenderingServer.EnvironmentToneMapper
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentToneMapper.Aces
  - Godot.RenderingServer.EnvironmentToneMapper.Agx
  - Godot.RenderingServer.EnvironmentToneMapper.Filmic
  - Godot.RenderingServer.EnvironmentToneMapper.Linear
  - Godot.RenderingServer.EnvironmentToneMapper.Reinhard
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentToneMapper
  nameWithType: RenderingServer.EnvironmentToneMapper
  fullName: Godot.RenderingServer.EnvironmentToneMapper
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentToneMapper : long'
    content.vb: Public Enum RenderingServer.EnvironmentToneMapper As Long
- uid: Godot.RenderingServer.EnvironmentToneMapper.Linear
  commentId: F:Godot.RenderingServer.EnvironmentToneMapper.Linear
  id: Linear
  parent: Godot.RenderingServer.EnvironmentToneMapper
  langs:
  - csharp
  - vb
  name: Linear
  nameWithType: RenderingServer.EnvironmentToneMapper.Linear
  fullName: Godot.RenderingServer.EnvironmentToneMapper.Linear
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Linear = 0
    return:
      type: Godot.RenderingServer.EnvironmentToneMapper
- uid: Godot.RenderingServer.EnvironmentToneMapper.Reinhard
  commentId: F:Godot.RenderingServer.EnvironmentToneMapper.Reinhard
  id: Reinhard
  parent: Godot.RenderingServer.EnvironmentToneMapper
  langs:
  - csharp
  - vb
  name: Reinhard
  nameWithType: RenderingServer.EnvironmentToneMapper.Reinhard
  fullName: Godot.RenderingServer.EnvironmentToneMapper.Reinhard
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Reinhard = 1
    return:
      type: Godot.RenderingServer.EnvironmentToneMapper
- uid: Godot.RenderingServer.EnvironmentToneMapper.Filmic
  commentId: F:Godot.RenderingServer.EnvironmentToneMapper.Filmic
  id: Filmic
  parent: Godot.RenderingServer.EnvironmentToneMapper
  langs:
  - csharp
  - vb
  name: Filmic
  nameWithType: RenderingServer.EnvironmentToneMapper.Filmic
  fullName: Godot.RenderingServer.EnvironmentToneMapper.Filmic
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Filmic = 2
    return:
      type: Godot.RenderingServer.EnvironmentToneMapper
- uid: Godot.RenderingServer.EnvironmentToneMapper.Aces
  commentId: F:Godot.RenderingServer.EnvironmentToneMapper.Aces
  id: Aces
  parent: Godot.RenderingServer.EnvironmentToneMapper
  langs:
  - csharp
  - vb
  name: Aces
  nameWithType: RenderingServer.EnvironmentToneMapper.Aces
  fullName: Godot.RenderingServer.EnvironmentToneMapper.Aces
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Aces = 3
    return:
      type: Godot.RenderingServer.EnvironmentToneMapper
- uid: Godot.RenderingServer.EnvironmentToneMapper.Agx
  commentId: F:Godot.RenderingServer.EnvironmentToneMapper.Agx
  id: Agx
  parent: Godot.RenderingServer.EnvironmentToneMapper
  langs:
  - csharp
  - vb
  name: Agx
  nameWithType: RenderingServer.EnvironmentToneMapper.Agx
  fullName: Godot.RenderingServer.EnvironmentToneMapper.Agx
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Agx = 4
    return:
      type: Godot.RenderingServer.EnvironmentToneMapper
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentToneMapper
  commentId: T:Godot.RenderingServer.EnvironmentToneMapper
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentToneMapper
  nameWithType: RenderingServer.EnvironmentToneMapper
  fullName: Godot.RenderingServer.EnvironmentToneMapper
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentToneMapper
    name: EnvironmentToneMapper
    isExternal: true
    href: Godot.RenderingServer.EnvironmentToneMapper.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentToneMapper
    name: EnvironmentToneMapper
    isExternal: true
    href: Godot.RenderingServer.EnvironmentToneMapper.html
