### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiRayCount
  id: RenderingServer.EnvironmentSdfgiRayCount
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count128
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count16
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count32
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count4
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count64
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count8
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Count96
  - Godot.RenderingServer.EnvironmentSdfgiRayCount.Max
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentSdfgiRayCount
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentSdfgiRayCount : long'
    content.vb: Public Enum RenderingServer.EnvironmentSdfgiRayCount As Long
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count4
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count4
  id: Count4
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count4
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count4
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count4
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count4 = 0
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count8
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count8
  id: Count8
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count8
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count8
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count8
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count8 = 1
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count16
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count16
  id: Count16
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count16
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count16
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count16
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count16 = 2
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count32
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count32
  id: Count32
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count32
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count32
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count32
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count32 = 3
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count64
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count64
  id: Count64
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count64
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count64
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count64
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count64 = 4
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count96
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count96
  id: Count96
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count96
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count96
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count96
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count96 = 5
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count128
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Count128
  id: Count128
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Count128
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Count128
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Count128
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Count128 = 6
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount.Max
  commentId: F:Godot.RenderingServer.EnvironmentSdfgiRayCount.Max
  id: Max
  parent: Godot.RenderingServer.EnvironmentSdfgiRayCount
  langs:
  - csharp
  - vb
  name: Max
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount.Max
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount.Max
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Max = 7
    return:
      type: Godot.RenderingServer.EnvironmentSdfgiRayCount
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentSdfgiRayCount
  commentId: T:Godot.RenderingServer.EnvironmentSdfgiRayCount
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentSdfgiRayCount
  nameWithType: RenderingServer.EnvironmentSdfgiRayCount
  fullName: Godot.RenderingServer.EnvironmentSdfgiRayCount
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiRayCount
    name: EnvironmentSdfgiRayCount
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiRayCount.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentSdfgiRayCount
    name: EnvironmentSdfgiRayCount
    isExternal: true
    href: Godot.RenderingServer.EnvironmentSdfgiRayCount.html
