### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode
  commentId: T:Godot.RenderingServer.EnvironmentGlowBlendMode
  id: RenderingServer.EnvironmentGlowBlendMode
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentGlowBlendMode.Additive
  - Godot.RenderingServer.EnvironmentGlowBlendMode.Mix
  - Godot.RenderingServer.EnvironmentGlowBlendMode.Replace
  - Godot.RenderingServer.EnvironmentGlowBlendMode.Screen
  - Godot.RenderingServer.EnvironmentGlowBlendMode.Softlight
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentGlowBlendMode
  nameWithType: RenderingServer.EnvironmentGlowBlendMode
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentGlowBlendMode : long'
    content.vb: Public Enum RenderingServer.EnvironmentGlowBlendMode As Long
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode.Additive
  commentId: F:Godot.RenderingServer.EnvironmentGlowBlendMode.Additive
  id: Additive
  parent: Godot.RenderingServer.EnvironmentGlowBlendMode
  langs:
  - csharp
  - vb
  name: Additive
  nameWithType: RenderingServer.EnvironmentGlowBlendMode.Additive
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode.Additive
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Additive = 0
    return:
      type: Godot.RenderingServer.EnvironmentGlowBlendMode
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode.Screen
  commentId: F:Godot.RenderingServer.EnvironmentGlowBlendMode.Screen
  id: Screen
  parent: Godot.RenderingServer.EnvironmentGlowBlendMode
  langs:
  - csharp
  - vb
  name: Screen
  nameWithType: RenderingServer.EnvironmentGlowBlendMode.Screen
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode.Screen
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Screen = 1
    return:
      type: Godot.RenderingServer.EnvironmentGlowBlendMode
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode.Softlight
  commentId: F:Godot.RenderingServer.EnvironmentGlowBlendMode.Softlight
  id: Softlight
  parent: Godot.RenderingServer.EnvironmentGlowBlendMode
  langs:
  - csharp
  - vb
  name: Softlight
  nameWithType: RenderingServer.EnvironmentGlowBlendMode.Softlight
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode.Softlight
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Softlight = 2
    return:
      type: Godot.RenderingServer.EnvironmentGlowBlendMode
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode.Replace
  commentId: F:Godot.RenderingServer.EnvironmentGlowBlendMode.Replace
  id: Replace
  parent: Godot.RenderingServer.EnvironmentGlowBlendMode
  langs:
  - csharp
  - vb
  name: Replace
  nameWithType: RenderingServer.EnvironmentGlowBlendMode.Replace
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode.Replace
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Replace = 3
    return:
      type: Godot.RenderingServer.EnvironmentGlowBlendMode
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode.Mix
  commentId: F:Godot.RenderingServer.EnvironmentGlowBlendMode.Mix
  id: Mix
  parent: Godot.RenderingServer.EnvironmentGlowBlendMode
  langs:
  - csharp
  - vb
  name: Mix
  nameWithType: RenderingServer.EnvironmentGlowBlendMode.Mix
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode.Mix
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Mix = 4
    return:
      type: Godot.RenderingServer.EnvironmentGlowBlendMode
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentGlowBlendMode
  commentId: T:Godot.RenderingServer.EnvironmentGlowBlendMode
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentGlowBlendMode
  nameWithType: RenderingServer.EnvironmentGlowBlendMode
  fullName: Godot.RenderingServer.EnvironmentGlowBlendMode
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentGlowBlendMode
    name: EnvironmentGlowBlendMode
    isExternal: true
    href: Godot.RenderingServer.EnvironmentGlowBlendMode.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentGlowBlendMode
    name: EnvironmentGlowBlendMode
    isExternal: true
    href: Godot.RenderingServer.EnvironmentGlowBlendMode.html
