### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentReflectionSource
  commentId: T:Godot.RenderingServer.EnvironmentReflectionSource
  id: RenderingServer.EnvironmentReflectionSource
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentReflectionSource.Bg
  - Godot.RenderingServer.EnvironmentReflectionSource.Disabled
  - Godot.RenderingServer.EnvironmentReflectionSource.Sky
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentReflectionSource
  nameWithType: RenderingServer.EnvironmentReflectionSource
  fullName: Godot.RenderingServer.EnvironmentReflectionSource
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentReflectionSource : long'
    content.vb: Public Enum RenderingServer.EnvironmentReflectionSource As Long
- uid: Godot.RenderingServer.EnvironmentReflectionSource.Bg
  commentId: F:Godot.RenderingServer.EnvironmentReflectionSource.Bg
  id: Bg
  parent: Godot.RenderingServer.EnvironmentReflectionSource
  langs:
  - csharp
  - vb
  name: Bg
  nameWithType: RenderingServer.EnvironmentReflectionSource.Bg
  fullName: Godot.RenderingServer.EnvironmentReflectionSource.Bg
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Bg = 0
    return:
      type: Godot.RenderingServer.EnvironmentReflectionSource
- uid: Godot.RenderingServer.EnvironmentReflectionSource.Disabled
  commentId: F:Godot.RenderingServer.EnvironmentReflectionSource.Disabled
  id: Disabled
  parent: Godot.RenderingServer.EnvironmentReflectionSource
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RenderingServer.EnvironmentReflectionSource.Disabled
  fullName: Godot.RenderingServer.EnvironmentReflectionSource.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 1
    return:
      type: Godot.RenderingServer.EnvironmentReflectionSource
- uid: Godot.RenderingServer.EnvironmentReflectionSource.Sky
  commentId: F:Godot.RenderingServer.EnvironmentReflectionSource.Sky
  id: Sky
  parent: Godot.RenderingServer.EnvironmentReflectionSource
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: RenderingServer.EnvironmentReflectionSource.Sky
  fullName: Godot.RenderingServer.EnvironmentReflectionSource.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 2
    return:
      type: Godot.RenderingServer.EnvironmentReflectionSource
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentReflectionSource
  commentId: T:Godot.RenderingServer.EnvironmentReflectionSource
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentReflectionSource
  nameWithType: RenderingServer.EnvironmentReflectionSource
  fullName: Godot.RenderingServer.EnvironmentReflectionSource
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentReflectionSource
    name: EnvironmentReflectionSource
    isExternal: true
    href: Godot.RenderingServer.EnvironmentReflectionSource.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentReflectionSource
    name: EnvironmentReflectionSource
    isExternal: true
    href: Godot.RenderingServer.EnvironmentReflectionSource.html
