### YamlMime:ManagedReference
items:
- uid: Godot.Environment.FogModeEnum
  commentId: T:Godot.Environment.FogModeEnum
  id: Environment.FogModeEnum
  parent: Godot
  children:
  - Godot.Environment.FogModeEnum.Depth
  - Godot.Environment.FogModeEnum.Exponential
  langs:
  - csharp
  - vb
  name: Environment.FogModeEnum
  nameWithType: Environment.FogModeEnum
  fullName: Godot.Environment.FogModeEnum
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.FogModeEnum : long'
    content.vb: Public Enum Environment.FogModeEnum As Long
- uid: Godot.Environment.FogModeEnum.Exponential
  commentId: F:Godot.Environment.FogModeEnum.Exponential
  id: Exponential
  parent: Godot.Environment.FogModeEnum
  langs:
  - csharp
  - vb
  name: Exponential
  nameWithType: Environment.FogModeEnum.Exponential
  fullName: Godot.Environment.FogModeEnum.Exponential
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Exponential = 0
    return:
      type: Godot.Environment.FogModeEnum
- uid: Godot.Environment.FogModeEnum.Depth
  commentId: F:Godot.Environment.FogModeEnum.Depth
  id: Depth
  parent: Godot.Environment.FogModeEnum
  langs:
  - csharp
  - vb
  name: Depth
  nameWithType: Environment.FogModeEnum.Depth
  fullName: Godot.Environment.FogModeEnum.Depth
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Depth = 1
    return:
      type: Godot.Environment.FogModeEnum
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.FogModeEnum
  commentId: T:Godot.Environment.FogModeEnum
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.FogModeEnum
  nameWithType: Environment.FogModeEnum
  fullName: Godot.Environment.FogModeEnum
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.FogModeEnum
    name: FogModeEnum
    isExternal: true
    href: Godot.Environment.FogModeEnum.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.FogModeEnum
    name: FogModeEnum
    isExternal: true
    href: Godot.Environment.FogModeEnum.html
