### YamlMime:ManagedReference
items:
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  commentId: T:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  id: SceneTree.NodeConfigurationWarningChangedEventHandler
  parent: Godot
  children:
  - Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor(System.Object,System.IntPtr)
  - Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Godot.Node,System.AsyncCallback,System.Object)
  - Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke(System.IAsyncResult)
  - Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke(Godot.Node)
  langs:
  - csharp
  - vb
  name: SceneTree.NodeConfigurationWarningChangedEventHandler
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  type: Delegate
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public delegate void SceneTree.NodeConfigurationWarningChangedEventHandler(Node node)
    parameters:
    - id: node
      type: Godot.Node
    content.vb: Public Delegate Sub SceneTree.NodeConfigurationWarningChangedEventHandler(node As Node)
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor(System.Object,System.IntPtr)
  commentId: M:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor(System.Object,System.IntPtr)
  id: '#ctor(System.Object,System.IntPtr)'
  parent: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  langs:
  - csharp
  - vb
  name: NodeConfigurationWarningChangedEventHandler(object, nint)
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.NodeConfigurationWarningChangedEventHandler(object, nint)
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.NodeConfigurationWarningChangedEventHandler(object, nint)
  type: Constructor
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public NodeConfigurationWarningChangedEventHandler(object @object, nint method)
    parameters:
    - id: object
      type: System.Object
    - id: method
      type: System.IntPtr
    content.vb: Public Sub New([object] As Object, method As IntPtr)
  overload: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor*
  nameWithType.vb: SceneTree.NodeConfigurationWarningChangedEventHandler.New(Object, IntPtr)
  fullName.vb: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.New(Object, System.IntPtr)
  name.vb: New(Object, IntPtr)
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke(Godot.Node)
  commentId: M:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke(Godot.Node)
  id: Invoke(Godot.Node)
  parent: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  langs:
  - csharp
  - vb
  name: Invoke(Node)
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke(Node)
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke(Godot.Node)
  type: Method
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public virtual void Invoke(Node node)
    parameters:
    - id: node
      type: Godot.Node
    content.vb: Public Overridable Sub Invoke(node As Node)
  overload: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke*
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Godot.Node,System.AsyncCallback,System.Object)
  commentId: M:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Godot.Node,System.AsyncCallback,System.Object)
  id: BeginInvoke(Godot.Node,System.AsyncCallback,System.Object)
  parent: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  langs:
  - csharp
  - vb
  name: BeginInvoke(Node, AsyncCallback, object)
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Node, AsyncCallback, object)
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Godot.Node, System.AsyncCallback, object)
  type: Method
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public virtual IAsyncResult BeginInvoke(Node node, AsyncCallback callback, object @object)
    parameters:
    - id: node
      type: Godot.Node
    - id: callback
      type: System.AsyncCallback
    - id: object
      type: System.Object
    return:
      type: System.IAsyncResult
    content.vb: Public Overridable Function BeginInvoke(node As Node, callback As AsyncCallback, [object] As Object) As IAsyncResult
  overload: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke*
  nameWithType.vb: SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Node, AsyncCallback, Object)
  fullName.vb: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke(Godot.Node, System.AsyncCallback, Object)
  name.vb: BeginInvoke(Node, AsyncCallback, Object)
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke(System.IAsyncResult)
  commentId: M:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke(System.IAsyncResult)
  id: EndInvoke(System.IAsyncResult)
  parent: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler
  langs:
  - csharp
  - vb
  name: EndInvoke(IAsyncResult)
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke(IAsyncResult)
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke(System.IAsyncResult)
  type: Method
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: public virtual void EndInvoke(IAsyncResult result)
    parameters:
    - id: result
      type: System.IAsyncResult
    content.vb: Public Overridable Sub EndInvoke(result As IAsyncResult)
  overload: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke*
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Node
  commentId: T:Godot.Node
  parent: Godot
  isExternal: true
  href: Godot.Node.html
  name: Node
  nameWithType: Node
  fullName: Godot.Node
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor*
  commentId: Overload:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.#ctor
  isExternal: true
  href: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.html#Godot_SceneTree_NodeConfigurationWarningChangedEventHandler__ctor_System_Object_System_IntPtr_
  name: NodeConfigurationWarningChangedEventHandler
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.NodeConfigurationWarningChangedEventHandler
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.NodeConfigurationWarningChangedEventHandler
  nameWithType.vb: SceneTree.NodeConfigurationWarningChangedEventHandler.New
  fullName.vb: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.New
  name.vb: New
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.intptr
  name: nint
  nameWithType: nint
  fullName: nint
  nameWithType.vb: IntPtr
  fullName.vb: System.IntPtr
  name.vb: IntPtr
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke*
  commentId: Overload:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke
  isExternal: true
  href: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.html#Godot_SceneTree_NodeConfigurationWarningChangedEventHandler_Invoke_Godot_Node_
  name: Invoke
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.Invoke
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke*
  commentId: Overload:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke
  isExternal: true
  href: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.html#Godot_SceneTree_NodeConfigurationWarningChangedEventHandler_BeginInvoke_Godot_Node_System_AsyncCallback_System_Object_
  name: BeginInvoke
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.BeginInvoke
- uid: System.AsyncCallback
  commentId: T:System.AsyncCallback
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.asynccallback
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.IAsyncResult
  commentId: T:System.IAsyncResult
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncresult
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke*
  commentId: Overload:Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke
  isExternal: true
  href: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.html#Godot_SceneTree_NodeConfigurationWarningChangedEventHandler_EndInvoke_System_IAsyncResult_
  name: EndInvoke
  nameWithType: SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke
  fullName: Godot.SceneTree.NodeConfigurationWarningChangedEventHandler.EndInvoke
