### YamlMime:ManagedReference
items:
- uid: Godot.OpenXRInterface.PerfSettingsLevel
  commentId: T:Godot.OpenXRInterface.PerfSettingsLevel
  id: OpenXRInterface.PerfSettingsLevel
  parent: Godot
  children:
  - Godot.OpenXRInterface.PerfSettingsLevel.Boost
  - Godot.OpenXRInterface.PerfSettingsLevel.PowerSavings
  - Godot.OpenXRInterface.PerfSettingsLevel.SustainedHigh
  - Godot.OpenXRInterface.PerfSettingsLevel.SustainedLow
  langs:
  - csharp
  - vb
  name: OpenXRInterface.PerfSettingsLevel
  nameWithType: OpenXRInterface.PerfSettingsLevel
  fullName: Godot.OpenXRInterface.PerfSettingsLevel
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum OpenXRInterface.PerfSettingsLevel : long'
    content.vb: Public Enum OpenXRInterface.PerfSettingsLevel As Long
- uid: Godot.OpenXRInterface.PerfSettingsLevel.PowerSavings
  commentId: F:Godot.OpenXRInterface.PerfSettingsLevel.PowerSavings
  id: PowerSavings
  parent: Godot.OpenXRInterface.PerfSettingsLevel
  langs:
  - csharp
  - vb
  name: PowerSavings
  nameWithType: OpenXRInterface.PerfSettingsLevel.PowerSavings
  fullName: Godot.OpenXRInterface.PerfSettingsLevel.PowerSavings
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: PowerSavings = 0
    return:
      type: Godot.OpenXRInterface.PerfSettingsLevel
- uid: Godot.OpenXRInterface.PerfSettingsLevel.SustainedLow
  commentId: F:Godot.OpenXRInterface.PerfSettingsLevel.SustainedLow
  id: SustainedLow
  parent: Godot.OpenXRInterface.PerfSettingsLevel
  langs:
  - csharp
  - vb
  name: SustainedLow
  nameWithType: OpenXRInterface.PerfSettingsLevel.SustainedLow
  fullName: Godot.OpenXRInterface.PerfSettingsLevel.SustainedLow
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: SustainedLow = 1
    return:
      type: Godot.OpenXRInterface.PerfSettingsLevel
- uid: Godot.OpenXRInterface.PerfSettingsLevel.SustainedHigh
  commentId: F:Godot.OpenXRInterface.PerfSettingsLevel.SustainedHigh
  id: SustainedHigh
  parent: Godot.OpenXRInterface.PerfSettingsLevel
  langs:
  - csharp
  - vb
  name: SustainedHigh
  nameWithType: OpenXRInterface.PerfSettingsLevel.SustainedHigh
  fullName: Godot.OpenXRInterface.PerfSettingsLevel.SustainedHigh
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: SustainedHigh = 2
    return:
      type: Godot.OpenXRInterface.PerfSettingsLevel
- uid: Godot.OpenXRInterface.PerfSettingsLevel.Boost
  commentId: F:Godot.OpenXRInterface.PerfSettingsLevel.Boost
  id: Boost
  parent: Godot.OpenXRInterface.PerfSettingsLevel
  langs:
  - csharp
  - vb
  name: Boost
  nameWithType: OpenXRInterface.PerfSettingsLevel.Boost
  fullName: Godot.OpenXRInterface.PerfSettingsLevel.Boost
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Boost = 3
    return:
      type: Godot.OpenXRInterface.PerfSettingsLevel
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.OpenXRInterface.PerfSettingsLevel
  commentId: T:Godot.OpenXRInterface.PerfSettingsLevel
  parent: Godot
  isExternal: true
  href: Godot.OpenXRInterface.html
  name: OpenXRInterface.PerfSettingsLevel
  nameWithType: OpenXRInterface.PerfSettingsLevel
  fullName: Godot.OpenXRInterface.PerfSettingsLevel
  spec.csharp:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsLevel
    name: PerfSettingsLevel
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsLevel.html
  spec.vb:
  - uid: Godot.OpenXRInterface
    name: OpenXRInterface
    isExternal: true
    href: Godot.OpenXRInterface.html
  - name: .
  - uid: Godot.OpenXRInterface.PerfSettingsLevel
    name: PerfSettingsLevel
    isExternal: true
    href: Godot.OpenXRInterface.PerfSettingsLevel.html
