### YamlMime:ManagedReference
items:
- uid: Godot.RenderingServer.EnvironmentAmbientSource
  commentId: T:Godot.RenderingServer.EnvironmentAmbientSource
  id: RenderingServer.EnvironmentAmbientSource
  parent: Godot
  children:
  - Godot.RenderingServer.EnvironmentAmbientSource.Bg
  - Godot.RenderingServer.EnvironmentAmbientSource.Color
  - Godot.RenderingServer.EnvironmentAmbientSource.Disabled
  - Godot.RenderingServer.EnvironmentAmbientSource.Sky
  langs:
  - csharp
  - vb
  name: RenderingServer.EnvironmentAmbientSource
  nameWithType: RenderingServer.EnvironmentAmbientSource
  fullName: Godot.RenderingServer.EnvironmentAmbientSource
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum RenderingServer.EnvironmentAmbientSource : long'
    content.vb: Public Enum RenderingServer.EnvironmentAmbientSource As Long
- uid: Godot.RenderingServer.EnvironmentAmbientSource.Bg
  commentId: F:Godot.RenderingServer.EnvironmentAmbientSource.Bg
  id: Bg
  parent: Godot.RenderingServer.EnvironmentAmbientSource
  langs:
  - csharp
  - vb
  name: Bg
  nameWithType: RenderingServer.EnvironmentAmbientSource.Bg
  fullName: Godot.RenderingServer.EnvironmentAmbientSource.Bg
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Bg = 0
    return:
      type: Godot.RenderingServer.EnvironmentAmbientSource
- uid: Godot.RenderingServer.EnvironmentAmbientSource.Disabled
  commentId: F:Godot.RenderingServer.EnvironmentAmbientSource.Disabled
  id: Disabled
  parent: Godot.RenderingServer.EnvironmentAmbientSource
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: RenderingServer.EnvironmentAmbientSource.Disabled
  fullName: Godot.RenderingServer.EnvironmentAmbientSource.Disabled
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Disabled = 1
    return:
      type: Godot.RenderingServer.EnvironmentAmbientSource
- uid: Godot.RenderingServer.EnvironmentAmbientSource.Color
  commentId: F:Godot.RenderingServer.EnvironmentAmbientSource.Color
  id: Color
  parent: Godot.RenderingServer.EnvironmentAmbientSource
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: RenderingServer.EnvironmentAmbientSource.Color
  fullName: Godot.RenderingServer.EnvironmentAmbientSource.Color
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Color = 2
    return:
      type: Godot.RenderingServer.EnvironmentAmbientSource
- uid: Godot.RenderingServer.EnvironmentAmbientSource.Sky
  commentId: F:Godot.RenderingServer.EnvironmentAmbientSource.Sky
  id: Sky
  parent: Godot.RenderingServer.EnvironmentAmbientSource
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: RenderingServer.EnvironmentAmbientSource.Sky
  fullName: Godot.RenderingServer.EnvironmentAmbientSource.Sky
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Sky = 3
    return:
      type: Godot.RenderingServer.EnvironmentAmbientSource
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.RenderingServer.EnvironmentAmbientSource
  commentId: T:Godot.RenderingServer.EnvironmentAmbientSource
  parent: Godot
  isExternal: true
  href: Godot.RenderingServer.html
  name: RenderingServer.EnvironmentAmbientSource
  nameWithType: RenderingServer.EnvironmentAmbientSource
  fullName: Godot.RenderingServer.EnvironmentAmbientSource
  spec.csharp:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentAmbientSource
    name: EnvironmentAmbientSource
    isExternal: true
    href: Godot.RenderingServer.EnvironmentAmbientSource.html
  spec.vb:
  - uid: Godot.RenderingServer
    name: RenderingServer
    isExternal: true
    href: Godot.RenderingServer.html
  - name: .
  - uid: Godot.RenderingServer.EnvironmentAmbientSource
    name: EnvironmentAmbientSource
    isExternal: true
    href: Godot.RenderingServer.EnvironmentAmbientSource.html
