### YamlMime:ManagedReference
items:
- uid: Godot.Environment.ToneMapper
  commentId: T:Godot.Environment.ToneMapper
  id: Environment.ToneMapper
  parent: Godot
  children:
  - Godot.Environment.ToneMapper.Aces
  - Godot.Environment.ToneMapper.Agx
  - Godot.Environment.ToneMapper.Filmic
  - Godot.Environment.ToneMapper.Linear
  - Godot.Environment.ToneMapper.Reinhardt
  langs:
  - csharp
  - vb
  name: Environment.ToneMapper
  nameWithType: Environment.ToneMapper
  fullName: Godot.Environment.ToneMapper
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.ToneMapper : long'
    content.vb: Public Enum Environment.ToneMapper As Long
- uid: Godot.Environment.ToneMapper.Linear
  commentId: F:Godot.Environment.ToneMapper.Linear
  id: Linear
  parent: Godot.Environment.ToneMapper
  langs:
  - csharp
  - vb
  name: Linear
  nameWithType: Environment.ToneMapper.Linear
  fullName: Godot.Environment.ToneMapper.Linear
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Linear = 0
    return:
      type: Godot.Environment.ToneMapper
- uid: Godot.Environment.ToneMapper.Reinhardt
  commentId: F:Godot.Environment.ToneMapper.Reinhardt
  id: Reinhardt
  parent: Godot.Environment.ToneMapper
  langs:
  - csharp
  - vb
  name: Reinhardt
  nameWithType: Environment.ToneMapper.Reinhardt
  fullName: Godot.Environment.ToneMapper.Reinhardt
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Reinhardt = 1
    return:
      type: Godot.Environment.ToneMapper
- uid: Godot.Environment.ToneMapper.Filmic
  commentId: F:Godot.Environment.ToneMapper.Filmic
  id: Filmic
  parent: Godot.Environment.ToneMapper
  langs:
  - csharp
  - vb
  name: Filmic
  nameWithType: Environment.ToneMapper.Filmic
  fullName: Godot.Environment.ToneMapper.Filmic
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Filmic = 2
    return:
      type: Godot.Environment.ToneMapper
- uid: Godot.Environment.ToneMapper.Aces
  commentId: F:Godot.Environment.ToneMapper.Aces
  id: Aces
  parent: Godot.Environment.ToneMapper
  langs:
  - csharp
  - vb
  name: Aces
  nameWithType: Environment.ToneMapper.Aces
  fullName: Godot.Environment.ToneMapper.Aces
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Aces = 3
    return:
      type: Godot.Environment.ToneMapper
- uid: Godot.Environment.ToneMapper.Agx
  commentId: F:Godot.Environment.ToneMapper.Agx
  id: Agx
  parent: Godot.Environment.ToneMapper
  langs:
  - csharp
  - vb
  name: Agx
  nameWithType: Environment.ToneMapper.Agx
  fullName: Godot.Environment.ToneMapper.Agx
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Agx = 4
    return:
      type: Godot.Environment.ToneMapper
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.ToneMapper
  commentId: T:Godot.Environment.ToneMapper
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.ToneMapper
  nameWithType: Environment.ToneMapper
  fullName: Godot.Environment.ToneMapper
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.ToneMapper
    name: ToneMapper
    isExternal: true
    href: Godot.Environment.ToneMapper.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.ToneMapper
    name: ToneMapper
    isExternal: true
    href: Godot.Environment.ToneMapper.html
