### YamlMime:ManagedReference
items:
- uid: Godot.Environment.SdfgiyScale
  commentId: T:Godot.Environment.SdfgiyScale
  id: Environment.SdfgiyScale
  parent: Godot
  children:
  - Godot.Environment.SdfgiyScale.Scale100Percent
  - Godot.Environment.SdfgiyScale.Scale50Percent
  - Godot.Environment.SdfgiyScale.Scale75Percent
  langs:
  - csharp
  - vb
  name: Environment.SdfgiyScale
  nameWithType: Environment.SdfgiyScale
  fullName: Godot.Environment.SdfgiyScale
  type: Enum
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: 'public enum Environment.SdfgiyScale : long'
    content.vb: Public Enum Environment.SdfgiyScale As Long
- uid: Godot.Environment.SdfgiyScale.Scale50Percent
  commentId: F:Godot.Environment.SdfgiyScale.Scale50Percent
  id: Scale50Percent
  parent: Godot.Environment.SdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale50Percent
  nameWithType: Environment.SdfgiyScale.Scale50Percent
  fullName: Godot.Environment.SdfgiyScale.Scale50Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale50Percent = 0
    return:
      type: Godot.Environment.SdfgiyScale
- uid: Godot.Environment.SdfgiyScale.Scale75Percent
  commentId: F:Godot.Environment.SdfgiyScale.Scale75Percent
  id: Scale75Percent
  parent: Godot.Environment.SdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale75Percent
  nameWithType: Environment.SdfgiyScale.Scale75Percent
  fullName: Godot.Environment.SdfgiyScale.Scale75Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale75Percent = 1
    return:
      type: Godot.Environment.SdfgiyScale
- uid: Godot.Environment.SdfgiyScale.Scale100Percent
  commentId: F:Godot.Environment.SdfgiyScale.Scale100Percent
  id: Scale100Percent
  parent: Godot.Environment.SdfgiyScale
  langs:
  - csharp
  - vb
  name: Scale100Percent
  nameWithType: Environment.SdfgiyScale.Scale100Percent
  fullName: Godot.Environment.SdfgiyScale.Scale100Percent
  type: Field
  assemblies:
  - GodotSharp
  namespace: Godot
  syntax:
    content: Scale100Percent = 2
    return:
      type: Godot.Environment.SdfgiyScale
references:
- uid: Godot
  commentId: N:Godot
  isExternal: true
  href: Godot.html
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: Godot.Environment.SdfgiyScale
  commentId: T:Godot.Environment.SdfgiyScale
  parent: Godot
  isExternal: true
  href: Godot.Environment.html
  name: Environment.SdfgiyScale
  nameWithType: Environment.SdfgiyScale
  fullName: Godot.Environment.SdfgiyScale
  spec.csharp:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.SdfgiyScale
    name: SdfgiyScale
    isExternal: true
    href: Godot.Environment.SdfgiyScale.html
  spec.vb:
  - uid: Godot.Environment
    name: Environment
    isExternal: true
    href: Godot.Environment.html
  - name: .
  - uid: Godot.Environment.SdfgiyScale
    name: SdfgiyScale
    isExternal: true
    href: Godot.Environment.SdfgiyScale.html
