### YamlMime:ManagedReference
items:
- uid: SzeneGenerator.CameraSettings
  commentId: T:SzeneGenerator.CameraSettings
  id: CameraSettings
  parent: SzeneGenerator
  children:
  - SzeneGenerator.CameraSettings.#ctor
  - SzeneGenerator.CameraSettings.MouseSensitivity
  - SzeneGenerator.CameraSettings.Presets
  - SzeneGenerator.CameraSettings.Speed
  - SzeneGenerator.CameraSettings.StartPresetId
  - SzeneGenerator.CameraSettings.TargetPresets
  langs:
  - csharp
  - vb
  name: CameraSettings
  nameWithType: CameraSettings
  fullName: SzeneGenerator.CameraSettings
  type: Class
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public class CameraSettings
    content.vb: Public Class CameraSettings
  inheritance:
  - System.Object
- uid: SzeneGenerator.CameraSettings.#ctor
  commentId: M:SzeneGenerator.CameraSettings.#ctor
  id: '#ctor'
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: CameraSettings()
  nameWithType: CameraSettings.CameraSettings()
  fullName: SzeneGenerator.CameraSettings.CameraSettings()
  type: Constructor
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public CameraSettings()
    content.vb: Public Sub New()
  overload: SzeneGenerator.CameraSettings.#ctor*
  nameWithType.vb: CameraSettings.New()
  fullName.vb: SzeneGenerator.CameraSettings.New()
  name.vb: New()
- uid: SzeneGenerator.CameraSettings.Speed
  commentId: P:SzeneGenerator.CameraSettings.Speed
  id: Speed
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: Speed
  nameWithType: CameraSettings.Speed
  fullName: SzeneGenerator.CameraSettings.Speed
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float Speed { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property Speed As Single
  overload: SzeneGenerator.CameraSettings.Speed*
- uid: SzeneGenerator.CameraSettings.MouseSensitivity
  commentId: P:SzeneGenerator.CameraSettings.MouseSensitivity
  id: MouseSensitivity
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: MouseSensitivity
  nameWithType: CameraSettings.MouseSensitivity
  fullName: SzeneGenerator.CameraSettings.MouseSensitivity
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float MouseSensitivity { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property MouseSensitivity As Single
  overload: SzeneGenerator.CameraSettings.MouseSensitivity*
- uid: SzeneGenerator.CameraSettings.StartPresetId
  commentId: P:SzeneGenerator.CameraSettings.StartPresetId
  id: StartPresetId
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: StartPresetId
  nameWithType: CameraSettings.StartPresetId
  fullName: SzeneGenerator.CameraSettings.StartPresetId
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public int StartPresetId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property StartPresetId As Integer
  overload: SzeneGenerator.CameraSettings.StartPresetId*
- uid: SzeneGenerator.CameraSettings.Presets
  commentId: P:SzeneGenerator.CameraSettings.Presets
  id: Presets
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: Presets
  nameWithType: CameraSettings.Presets
  fullName: SzeneGenerator.CameraSettings.Presets
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public Dictionary<int, (Vector3 pos, Vector3 rot)> Presets { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.Int32,System.ValueTuple{Godot.Vector3,Godot.Vector3}}
    content.vb: Public Property Presets As Dictionary(Of Integer, (pos As Vector3, rot As Vector3))
  overload: SzeneGenerator.CameraSettings.Presets*
- uid: SzeneGenerator.CameraSettings.TargetPresets
  commentId: P:SzeneGenerator.CameraSettings.TargetPresets
  id: TargetPresets
  parent: SzeneGenerator.CameraSettings
  langs:
  - csharp
  - vb
  name: TargetPresets
  nameWithType: CameraSettings.TargetPresets
  fullName: SzeneGenerator.CameraSettings.TargetPresets
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public Dictionary<int, CameraTargetPreset> TargetPresets { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.Int32,SzeneGenerator.CameraTargetPreset}
    content.vb: Public Property TargetPresets As Dictionary(Of Integer, CameraTargetPreset)
  overload: SzeneGenerator.CameraSettings.TargetPresets*
references:
- uid: SzeneGenerator
  commentId: N:SzeneGenerator
  isExternal: true
  href: SzeneGenerator.html
  name: SzeneGenerator
  nameWithType: SzeneGenerator
  fullName: SzeneGenerator
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SzeneGenerator.CameraSettings.#ctor*
  commentId: Overload:SzeneGenerator.CameraSettings.#ctor
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings__ctor
  name: CameraSettings
  nameWithType: CameraSettings.CameraSettings
  fullName: SzeneGenerator.CameraSettings.CameraSettings
  nameWithType.vb: CameraSettings.New
  fullName.vb: SzeneGenerator.CameraSettings.New
  name.vb: New
- uid: SzeneGenerator.CameraSettings.Speed*
  commentId: Overload:SzeneGenerator.CameraSettings.Speed
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings_Speed
  name: Speed
  nameWithType: CameraSettings.Speed
  fullName: SzeneGenerator.CameraSettings.Speed
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: SzeneGenerator.CameraSettings.MouseSensitivity*
  commentId: Overload:SzeneGenerator.CameraSettings.MouseSensitivity
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings_MouseSensitivity
  name: MouseSensitivity
  nameWithType: CameraSettings.MouseSensitivity
  fullName: SzeneGenerator.CameraSettings.MouseSensitivity
- uid: SzeneGenerator.CameraSettings.StartPresetId*
  commentId: Overload:SzeneGenerator.CameraSettings.StartPresetId
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings_StartPresetId
  name: StartPresetId
  nameWithType: CameraSettings.StartPresetId
  fullName: SzeneGenerator.CameraSettings.StartPresetId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: SzeneGenerator.CameraSettings.Presets*
  commentId: Overload:SzeneGenerator.CameraSettings.Presets
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings_Presets
  name: Presets
  nameWithType: CameraSettings.Presets
  fullName: SzeneGenerator.CameraSettings.Presets
- uid: System.Collections.Generic.Dictionary{System.Int32,System.ValueTuple{Godot.Vector3,Godot.Vector3}}
  commentId: T:System.Collections.Generic.Dictionary{System.Int32,System.ValueTuple{Godot.Vector3,Godot.Vector3}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<int, (Vector3 pos, Vector3 rot)>
  nameWithType: Dictionary<int, (Vector3 pos, Vector3 rot)>
  fullName: System.Collections.Generic.Dictionary<int, (Godot.Vector3 pos, Godot.Vector3 rot)>
  nameWithType.vb: Dictionary(Of Integer, (pos As Vector3, rot As Vector3))
  fullName.vb: System.Collections.Generic.Dictionary(Of Integer, (pos As Godot.Vector3, rot As Godot.Vector3))
  name.vb: Dictionary(Of Integer, (pos As Vector3, rot As Vector3))
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
  - name: ','
  - name: " "
  - name: (
  - uid: Godot.Vector3
    name: Vector3
    isExternal: true
  - name: " "
  - uid: System.ValueTuple{Godot.Vector3,Godot.Vector3}.pos
    name: pos
    isExternal: true
  - name: ','
  - name: " "
  - uid: Godot.Vector3
    name: Vector3
    isExternal: true
  - name: " "
  - uid: System.ValueTuple{Godot.Vector3,Godot.Vector3}.rot
    name: rot
    isExternal: true
  - name: )
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: ','
  - name: " "
  - name: (
  - uid: System.ValueTuple{Godot.Vector3,Godot.Vector3}.pos
    name: pos
    isExternal: true
  - name: " "
  - name: As
  - name: " "
  - uid: Godot.Vector3
    name: Vector3
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.ValueTuple{Godot.Vector3,Godot.Vector3}.rot
    name: rot
    isExternal: true
  - name: " "
  - name: As
  - name: " "
  - uid: Godot.Vector3
    name: Vector3
    isExternal: true
  - name: )
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
  spec.vb:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
- uid: SzeneGenerator.CameraSettings.TargetPresets*
  commentId: Overload:SzeneGenerator.CameraSettings.TargetPresets
  isExternal: true
  href: SzeneGenerator.CameraSettings.html#SzeneGenerator_CameraSettings_TargetPresets
  name: TargetPresets
  nameWithType: CameraSettings.TargetPresets
  fullName: SzeneGenerator.CameraSettings.TargetPresets
- uid: System.Collections.Generic.Dictionary{System.Int32,SzeneGenerator.CameraTargetPreset}
  commentId: T:System.Collections.Generic.Dictionary{System.Int32,SzeneGenerator.CameraTargetPreset}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: SzeneGenerator.CameraTargetPreset.html
  name: Dictionary<int, CameraTargetPreset>
  nameWithType: Dictionary<int, CameraTargetPreset>
  fullName: System.Collections.Generic.Dictionary<int, SzeneGenerator.CameraTargetPreset>
  nameWithType.vb: Dictionary(Of Integer, CameraTargetPreset)
  fullName.vb: System.Collections.Generic.Dictionary(Of Integer, SzeneGenerator.CameraTargetPreset)
  name.vb: Dictionary(Of Integer, CameraTargetPreset)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
  - name: ','
  - name: " "
  - uid: SzeneGenerator.CameraTargetPreset
    name: CameraTargetPreset
    isExternal: true
    href: SzeneGenerator.CameraTargetPreset.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
  - name: ','
  - name: " "
  - uid: SzeneGenerator.CameraTargetPreset
    name: CameraTargetPreset
    isExternal: true
    href: SzeneGenerator.CameraTargetPreset.html
  - name: )
