### YamlMime:ManagedReference
items:
- uid: SzeneGenerator.TerrainSettings
  commentId: T:SzeneGenerator.TerrainSettings
  id: TerrainSettings
  parent: SzeneGenerator
  children:
  - SzeneGenerator.TerrainSettings.#ctor
  - SzeneGenerator.TerrainSettings.ExportTargetCoordinates
  - SzeneGenerator.TerrainSettings.GetValidatedRegionSize
  - SzeneGenerator.TerrainSettings.HeightFactor
  - SzeneGenerator.TerrainSettings.MetersPerPixel
  - SzeneGenerator.TerrainSettings.NoiseScale
  - SzeneGenerator.TerrainSettings.Offset
  - SzeneGenerator.TerrainSettings.RegionId
  - SzeneGenerator.TerrainSettings.RegionSize
  - SzeneGenerator.TerrainSettings.Scale
  - SzeneGenerator.TerrainSettings.Seed
  - SzeneGenerator.TerrainSettings.TargetCoordinatesPath
  - SzeneGenerator.TerrainSettings.WorldBackground
  langs:
  - csharp
  - vb
  name: TerrainSettings
  nameWithType: TerrainSettings
  fullName: SzeneGenerator.TerrainSettings
  type: Class
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public class TerrainSettings
    content.vb: Public Class TerrainSettings
  inheritance:
  - System.Object
- uid: SzeneGenerator.TerrainSettings.GetValidatedRegionSize
  commentId: M:SzeneGenerator.TerrainSettings.GetValidatedRegionSize
  id: GetValidatedRegionSize
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: GetValidatedRegionSize()
  nameWithType: TerrainSettings.GetValidatedRegionSize()
  fullName: SzeneGenerator.TerrainSettings.GetValidatedRegionSize()
  type: Method
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public int GetValidatedRegionSize()
    return:
      type: System.Int32
    content.vb: Public Function GetValidatedRegionSize() As Integer
  overload: SzeneGenerator.TerrainSettings.GetValidatedRegionSize*
- uid: SzeneGenerator.TerrainSettings.#ctor
  commentId: M:SzeneGenerator.TerrainSettings.#ctor
  id: '#ctor'
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: TerrainSettings()
  nameWithType: TerrainSettings.TerrainSettings()
  fullName: SzeneGenerator.TerrainSettings.TerrainSettings()
  type: Constructor
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public TerrainSettings()
    content.vb: Public Sub New()
  overload: SzeneGenerator.TerrainSettings.#ctor*
  nameWithType.vb: TerrainSettings.New()
  fullName.vb: SzeneGenerator.TerrainSettings.New()
  name.vb: New()
- uid: SzeneGenerator.TerrainSettings.RegionSize
  commentId: P:SzeneGenerator.TerrainSettings.RegionSize
  id: RegionSize
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: RegionSize
  nameWithType: TerrainSettings.RegionSize
  fullName: SzeneGenerator.TerrainSettings.RegionSize
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public int RegionSize { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property RegionSize As Integer
  overload: SzeneGenerator.TerrainSettings.RegionSize*
- uid: SzeneGenerator.TerrainSettings.NoiseScale
  commentId: P:SzeneGenerator.TerrainSettings.NoiseScale
  id: NoiseScale
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: NoiseScale
  nameWithType: TerrainSettings.NoiseScale
  fullName: SzeneGenerator.TerrainSettings.NoiseScale
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float NoiseScale { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property NoiseScale As Single
  overload: SzeneGenerator.TerrainSettings.NoiseScale*
- uid: SzeneGenerator.TerrainSettings.HeightFactor
  commentId: P:SzeneGenerator.TerrainSettings.HeightFactor
  id: HeightFactor
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: HeightFactor
  nameWithType: TerrainSettings.HeightFactor
  fullName: SzeneGenerator.TerrainSettings.HeightFactor
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float HeightFactor { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property HeightFactor As Single
  overload: SzeneGenerator.TerrainSettings.HeightFactor*
- uid: SzeneGenerator.TerrainSettings.Offset
  commentId: P:SzeneGenerator.TerrainSettings.Offset
  id: Offset
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: Offset
  nameWithType: TerrainSettings.Offset
  fullName: SzeneGenerator.TerrainSettings.Offset
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float Offset { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property Offset As Single
  overload: SzeneGenerator.TerrainSettings.Offset*
- uid: SzeneGenerator.TerrainSettings.Scale
  commentId: P:SzeneGenerator.TerrainSettings.Scale
  id: Scale
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: Scale
  nameWithType: TerrainSettings.Scale
  fullName: SzeneGenerator.TerrainSettings.Scale
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float Scale { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property Scale As Single
  overload: SzeneGenerator.TerrainSettings.Scale*
- uid: SzeneGenerator.TerrainSettings.WorldBackground
  commentId: P:SzeneGenerator.TerrainSettings.WorldBackground
  id: WorldBackground
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: WorldBackground
  nameWithType: TerrainSettings.WorldBackground
  fullName: SzeneGenerator.TerrainSettings.WorldBackground
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public int WorldBackground { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property WorldBackground As Integer
  overload: SzeneGenerator.TerrainSettings.WorldBackground*
- uid: SzeneGenerator.TerrainSettings.MetersPerPixel
  commentId: P:SzeneGenerator.TerrainSettings.MetersPerPixel
  id: MetersPerPixel
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: MetersPerPixel
  nameWithType: TerrainSettings.MetersPerPixel
  fullName: SzeneGenerator.TerrainSettings.MetersPerPixel
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float MetersPerPixel { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property MetersPerPixel As Single
  overload: SzeneGenerator.TerrainSettings.MetersPerPixel*
- uid: SzeneGenerator.TerrainSettings.RegionId
  commentId: P:SzeneGenerator.TerrainSettings.RegionId
  id: RegionId
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: RegionId
  nameWithType: TerrainSettings.RegionId
  fullName: SzeneGenerator.TerrainSettings.RegionId
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public string RegionId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property RegionId As String
  overload: SzeneGenerator.TerrainSettings.RegionId*
- uid: SzeneGenerator.TerrainSettings.Seed
  commentId: P:SzeneGenerator.TerrainSettings.Seed
  id: Seed
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: Seed
  nameWithType: TerrainSettings.Seed
  fullName: SzeneGenerator.TerrainSettings.Seed
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public int Seed { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Seed As Integer
  overload: SzeneGenerator.TerrainSettings.Seed*
- uid: SzeneGenerator.TerrainSettings.ExportTargetCoordinates
  commentId: P:SzeneGenerator.TerrainSettings.ExportTargetCoordinates
  id: ExportTargetCoordinates
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: ExportTargetCoordinates
  nameWithType: TerrainSettings.ExportTargetCoordinates
  fullName: SzeneGenerator.TerrainSettings.ExportTargetCoordinates
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public bool ExportTargetCoordinates { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ExportTargetCoordinates As Boolean
  overload: SzeneGenerator.TerrainSettings.ExportTargetCoordinates*
- uid: SzeneGenerator.TerrainSettings.TargetCoordinatesPath
  commentId: P:SzeneGenerator.TerrainSettings.TargetCoordinatesPath
  id: TargetCoordinatesPath
  parent: SzeneGenerator.TerrainSettings
  langs:
  - csharp
  - vb
  name: TargetCoordinatesPath
  nameWithType: TerrainSettings.TargetCoordinatesPath
  fullName: SzeneGenerator.TerrainSettings.TargetCoordinatesPath
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public string TargetCoordinatesPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property TargetCoordinatesPath As String
  overload: SzeneGenerator.TerrainSettings.TargetCoordinatesPath*
references:
- uid: SzeneGenerator
  commentId: N:SzeneGenerator
  isExternal: true
  href: SzeneGenerator.html
  name: SzeneGenerator
  nameWithType: SzeneGenerator
  fullName: SzeneGenerator
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SzeneGenerator.TerrainSettings.GetValidatedRegionSize*
  commentId: Overload:SzeneGenerator.TerrainSettings.GetValidatedRegionSize
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_GetValidatedRegionSize
  name: GetValidatedRegionSize
  nameWithType: TerrainSettings.GetValidatedRegionSize
  fullName: SzeneGenerator.TerrainSettings.GetValidatedRegionSize
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: SzeneGenerator.TerrainSettings.#ctor*
  commentId: Overload:SzeneGenerator.TerrainSettings.#ctor
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings__ctor
  name: TerrainSettings
  nameWithType: TerrainSettings.TerrainSettings
  fullName: SzeneGenerator.TerrainSettings.TerrainSettings
  nameWithType.vb: TerrainSettings.New
  fullName.vb: SzeneGenerator.TerrainSettings.New
  name.vb: New
- uid: SzeneGenerator.TerrainSettings.RegionSize*
  commentId: Overload:SzeneGenerator.TerrainSettings.RegionSize
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_RegionSize
  name: RegionSize
  nameWithType: TerrainSettings.RegionSize
  fullName: SzeneGenerator.TerrainSettings.RegionSize
- uid: SzeneGenerator.TerrainSettings.NoiseScale*
  commentId: Overload:SzeneGenerator.TerrainSettings.NoiseScale
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_NoiseScale
  name: NoiseScale
  nameWithType: TerrainSettings.NoiseScale
  fullName: SzeneGenerator.TerrainSettings.NoiseScale
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: SzeneGenerator.TerrainSettings.HeightFactor*
  commentId: Overload:SzeneGenerator.TerrainSettings.HeightFactor
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_HeightFactor
  name: HeightFactor
  nameWithType: TerrainSettings.HeightFactor
  fullName: SzeneGenerator.TerrainSettings.HeightFactor
- uid: SzeneGenerator.TerrainSettings.Offset*
  commentId: Overload:SzeneGenerator.TerrainSettings.Offset
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_Offset
  name: Offset
  nameWithType: TerrainSettings.Offset
  fullName: SzeneGenerator.TerrainSettings.Offset
- uid: SzeneGenerator.TerrainSettings.Scale*
  commentId: Overload:SzeneGenerator.TerrainSettings.Scale
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_Scale
  name: Scale
  nameWithType: TerrainSettings.Scale
  fullName: SzeneGenerator.TerrainSettings.Scale
- uid: SzeneGenerator.TerrainSettings.WorldBackground*
  commentId: Overload:SzeneGenerator.TerrainSettings.WorldBackground
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_WorldBackground
  name: WorldBackground
  nameWithType: TerrainSettings.WorldBackground
  fullName: SzeneGenerator.TerrainSettings.WorldBackground
- uid: SzeneGenerator.TerrainSettings.MetersPerPixel*
  commentId: Overload:SzeneGenerator.TerrainSettings.MetersPerPixel
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_MetersPerPixel
  name: MetersPerPixel
  nameWithType: TerrainSettings.MetersPerPixel
  fullName: SzeneGenerator.TerrainSettings.MetersPerPixel
- uid: SzeneGenerator.TerrainSettings.RegionId*
  commentId: Overload:SzeneGenerator.TerrainSettings.RegionId
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_RegionId
  name: RegionId
  nameWithType: TerrainSettings.RegionId
  fullName: SzeneGenerator.TerrainSettings.RegionId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: SzeneGenerator.TerrainSettings.Seed*
  commentId: Overload:SzeneGenerator.TerrainSettings.Seed
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_Seed
  name: Seed
  nameWithType: TerrainSettings.Seed
  fullName: SzeneGenerator.TerrainSettings.Seed
- uid: SzeneGenerator.TerrainSettings.ExportTargetCoordinates*
  commentId: Overload:SzeneGenerator.TerrainSettings.ExportTargetCoordinates
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_ExportTargetCoordinates
  name: ExportTargetCoordinates
  nameWithType: TerrainSettings.ExportTargetCoordinates
  fullName: SzeneGenerator.TerrainSettings.ExportTargetCoordinates
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: SzeneGenerator.TerrainSettings.TargetCoordinatesPath*
  commentId: Overload:SzeneGenerator.TerrainSettings.TargetCoordinatesPath
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html#SzeneGenerator_TerrainSettings_TargetCoordinatesPath
  name: TargetCoordinatesPath
  nameWithType: TerrainSettings.TargetCoordinatesPath
  fullName: SzeneGenerator.TerrainSettings.TargetCoordinatesPath
