### YamlMime:ManagedReference
items:
- uid: SzeneGenerator.GlobalSkySettings
  commentId: T:SzeneGenerator.GlobalSkySettings
  id: GlobalSkySettings
  parent: SzeneGenerator
  children:
  - SzeneGenerator.GlobalSkySettings.#ctor
  - SzeneGenerator.GlobalSkySettings.FogAdjustForRain
  - SzeneGenerator.GlobalSkySettings.RainBoxExtents
  - SzeneGenerator.GlobalSkySettings.RainEnabled
  - SzeneGenerator.GlobalSkySettings.RainFogDensity
  - SzeneGenerator.GlobalSkySettings.RainFogLightTint
  - SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
  - SzeneGenerator.GlobalSkySettings.RainOffset
  - SzeneGenerator.GlobalSkySettings.TimeOfDay
  langs:
  - csharp
  - vb
  name: GlobalSkySettings
  nameWithType: GlobalSkySettings
  fullName: SzeneGenerator.GlobalSkySettings
  type: Class
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public class GlobalSkySettings
    content.vb: Public Class GlobalSkySettings
  inheritance:
  - System.Object
- uid: SzeneGenerator.GlobalSkySettings.#ctor
  commentId: M:SzeneGenerator.GlobalSkySettings.#ctor
  id: '#ctor'
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: GlobalSkySettings()
  nameWithType: GlobalSkySettings.GlobalSkySettings()
  fullName: SzeneGenerator.GlobalSkySettings.GlobalSkySettings()
  type: Constructor
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public GlobalSkySettings()
    content.vb: Public Sub New()
  overload: SzeneGenerator.GlobalSkySettings.#ctor*
  nameWithType.vb: GlobalSkySettings.New()
  fullName.vb: SzeneGenerator.GlobalSkySettings.New()
  name.vb: New()
- uid: SzeneGenerator.GlobalSkySettings.RainEnabled
  commentId: P:SzeneGenerator.GlobalSkySettings.RainEnabled
  id: RainEnabled
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainEnabled
  nameWithType: GlobalSkySettings.RainEnabled
  fullName: SzeneGenerator.GlobalSkySettings.RainEnabled
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public bool RainEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RainEnabled As Boolean
  overload: SzeneGenerator.GlobalSkySettings.RainEnabled*
- uid: SzeneGenerator.GlobalSkySettings.RainOffset
  commentId: P:SzeneGenerator.GlobalSkySettings.RainOffset
  id: RainOffset
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainOffset
  nameWithType: GlobalSkySettings.RainOffset
  fullName: SzeneGenerator.GlobalSkySettings.RainOffset
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public Vector3 RainOffset { get; set; }
    parameters: []
    return:
      type: Godot.Vector3
    content.vb: Public Property RainOffset As Vector3
  overload: SzeneGenerator.GlobalSkySettings.RainOffset*
- uid: SzeneGenerator.GlobalSkySettings.RainBoxExtents
  commentId: P:SzeneGenerator.GlobalSkySettings.RainBoxExtents
  id: RainBoxExtents
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainBoxExtents
  nameWithType: GlobalSkySettings.RainBoxExtents
  fullName: SzeneGenerator.GlobalSkySettings.RainBoxExtents
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public Vector3 RainBoxExtents { get; set; }
    parameters: []
    return:
      type: Godot.Vector3
    content.vb: Public Property RainBoxExtents As Vector3
  overload: SzeneGenerator.GlobalSkySettings.RainBoxExtents*
- uid: SzeneGenerator.GlobalSkySettings.FogAdjustForRain
  commentId: P:SzeneGenerator.GlobalSkySettings.FogAdjustForRain
  id: FogAdjustForRain
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: FogAdjustForRain
  nameWithType: GlobalSkySettings.FogAdjustForRain
  fullName: SzeneGenerator.GlobalSkySettings.FogAdjustForRain
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public bool FogAdjustForRain { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property FogAdjustForRain As Boolean
  overload: SzeneGenerator.GlobalSkySettings.FogAdjustForRain*
- uid: SzeneGenerator.GlobalSkySettings.RainFogDensity
  commentId: P:SzeneGenerator.GlobalSkySettings.RainFogDensity
  id: RainFogDensity
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainFogDensity
  nameWithType: GlobalSkySettings.RainFogDensity
  fullName: SzeneGenerator.GlobalSkySettings.RainFogDensity
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float RainFogDensity { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property RainFogDensity As Single
  overload: SzeneGenerator.GlobalSkySettings.RainFogDensity*
- uid: SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
  commentId: P:SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
  id: RainFogSunAmountMultiplier
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainFogSunAmountMultiplier
  nameWithType: GlobalSkySettings.RainFogSunAmountMultiplier
  fullName: SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float RainFogSunAmountMultiplier { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property RainFogSunAmountMultiplier As Single
  overload: SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier*
- uid: SzeneGenerator.GlobalSkySettings.RainFogLightTint
  commentId: P:SzeneGenerator.GlobalSkySettings.RainFogLightTint
  id: RainFogLightTint
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: RainFogLightTint
  nameWithType: GlobalSkySettings.RainFogLightTint
  fullName: SzeneGenerator.GlobalSkySettings.RainFogLightTint
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public Color RainFogLightTint { get; set; }
    parameters: []
    return:
      type: Godot.Color
    content.vb: Public Property RainFogLightTint As Color
  overload: SzeneGenerator.GlobalSkySettings.RainFogLightTint*
- uid: SzeneGenerator.GlobalSkySettings.TimeOfDay
  commentId: P:SzeneGenerator.GlobalSkySettings.TimeOfDay
  id: TimeOfDay
  parent: SzeneGenerator.GlobalSkySettings
  langs:
  - csharp
  - vb
  name: TimeOfDay
  nameWithType: GlobalSkySettings.TimeOfDay
  fullName: SzeneGenerator.GlobalSkySettings.TimeOfDay
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public float TimeOfDay { get; set; }
    parameters: []
    return:
      type: System.Single
    content.vb: Public Property TimeOfDay As Single
  overload: SzeneGenerator.GlobalSkySettings.TimeOfDay*
references:
- uid: SzeneGenerator
  commentId: N:SzeneGenerator
  isExternal: true
  href: SzeneGenerator.html
  name: SzeneGenerator
  nameWithType: SzeneGenerator
  fullName: SzeneGenerator
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SzeneGenerator.GlobalSkySettings.#ctor*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.#ctor
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings__ctor
  name: GlobalSkySettings
  nameWithType: GlobalSkySettings.GlobalSkySettings
  fullName: SzeneGenerator.GlobalSkySettings.GlobalSkySettings
  nameWithType.vb: GlobalSkySettings.New
  fullName.vb: SzeneGenerator.GlobalSkySettings.New
  name.vb: New
- uid: SzeneGenerator.GlobalSkySettings.RainEnabled*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainEnabled
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainEnabled
  name: RainEnabled
  nameWithType: GlobalSkySettings.RainEnabled
  fullName: SzeneGenerator.GlobalSkySettings.RainEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: SzeneGenerator.GlobalSkySettings.RainOffset*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainOffset
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainOffset
  name: RainOffset
  nameWithType: GlobalSkySettings.RainOffset
  fullName: SzeneGenerator.GlobalSkySettings.RainOffset
- uid: Godot.Vector3
  commentId: T:Godot.Vector3
  parent: Godot
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: Godot.Vector3
- uid: Godot
  commentId: N:Godot
  isExternal: true
  name: Godot
  nameWithType: Godot
  fullName: Godot
- uid: SzeneGenerator.GlobalSkySettings.RainBoxExtents*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainBoxExtents
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainBoxExtents
  name: RainBoxExtents
  nameWithType: GlobalSkySettings.RainBoxExtents
  fullName: SzeneGenerator.GlobalSkySettings.RainBoxExtents
- uid: SzeneGenerator.GlobalSkySettings.FogAdjustForRain*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.FogAdjustForRain
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_FogAdjustForRain
  name: FogAdjustForRain
  nameWithType: GlobalSkySettings.FogAdjustForRain
  fullName: SzeneGenerator.GlobalSkySettings.FogAdjustForRain
- uid: SzeneGenerator.GlobalSkySettings.RainFogDensity*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainFogDensity
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainFogDensity
  name: RainFogDensity
  nameWithType: GlobalSkySettings.RainFogDensity
  fullName: SzeneGenerator.GlobalSkySettings.RainFogDensity
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainFogSunAmountMultiplier
  name: RainFogSunAmountMultiplier
  nameWithType: GlobalSkySettings.RainFogSunAmountMultiplier
  fullName: SzeneGenerator.GlobalSkySettings.RainFogSunAmountMultiplier
- uid: SzeneGenerator.GlobalSkySettings.RainFogLightTint*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.RainFogLightTint
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_RainFogLightTint
  name: RainFogLightTint
  nameWithType: GlobalSkySettings.RainFogLightTint
  fullName: SzeneGenerator.GlobalSkySettings.RainFogLightTint
- uid: Godot.Color
  commentId: T:Godot.Color
  parent: Godot
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: Godot.Color
- uid: SzeneGenerator.GlobalSkySettings.TimeOfDay*
  commentId: Overload:SzeneGenerator.GlobalSkySettings.TimeOfDay
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html#SzeneGenerator_GlobalSkySettings_TimeOfDay
  name: TimeOfDay
  nameWithType: GlobalSkySettings.TimeOfDay
  fullName: SzeneGenerator.GlobalSkySettings.TimeOfDay
