### YamlMime:ManagedReference
items:
- uid: SzeneGenerator.WorldSettings
  commentId: T:SzeneGenerator.WorldSettings
  id: WorldSettings
  parent: SzeneGenerator
  children:
  - SzeneGenerator.WorldSettings.#ctor
  - SzeneGenerator.WorldSettings.Camera
  - SzeneGenerator.WorldSettings.Sky
  - SzeneGenerator.WorldSettings.Terrain
  langs:
  - csharp
  - vb
  name: WorldSettings
  nameWithType: WorldSettings
  fullName: SzeneGenerator.WorldSettings
  type: Class
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  summary: Root configuration container for terrain, sky, and camera settings.
  example: []
  syntax:
    content: public class WorldSettings
    content.vb: Public Class WorldSettings
  inheritance:
  - System.Object
- uid: SzeneGenerator.WorldSettings.#ctor
  commentId: M:SzeneGenerator.WorldSettings.#ctor
  id: '#ctor'
  parent: SzeneGenerator.WorldSettings
  langs:
  - csharp
  - vb
  name: WorldSettings()
  nameWithType: WorldSettings.WorldSettings()
  fullName: SzeneGenerator.WorldSettings.WorldSettings()
  type: Constructor
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public WorldSettings()
    content.vb: Public Sub New()
  overload: SzeneGenerator.WorldSettings.#ctor*
  nameWithType.vb: WorldSettings.New()
  fullName.vb: SzeneGenerator.WorldSettings.New()
  name.vb: New()
- uid: SzeneGenerator.WorldSettings.Terrain
  commentId: P:SzeneGenerator.WorldSettings.Terrain
  id: Terrain
  parent: SzeneGenerator.WorldSettings
  langs:
  - csharp
  - vb
  name: Terrain
  nameWithType: WorldSettings.Terrain
  fullName: SzeneGenerator.WorldSettings.Terrain
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public TerrainSettings Terrain { get; set; }
    parameters: []
    return:
      type: SzeneGenerator.TerrainSettings
    content.vb: Public Property Terrain As TerrainSettings
  overload: SzeneGenerator.WorldSettings.Terrain*
- uid: SzeneGenerator.WorldSettings.Sky
  commentId: P:SzeneGenerator.WorldSettings.Sky
  id: Sky
  parent: SzeneGenerator.WorldSettings
  langs:
  - csharp
  - vb
  name: Sky
  nameWithType: WorldSettings.Sky
  fullName: SzeneGenerator.WorldSettings.Sky
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public GlobalSkySettings Sky { get; set; }
    parameters: []
    return:
      type: SzeneGenerator.GlobalSkySettings
    content.vb: Public Property Sky As GlobalSkySettings
  overload: SzeneGenerator.WorldSettings.Sky*
- uid: SzeneGenerator.WorldSettings.Camera
  commentId: P:SzeneGenerator.WorldSettings.Camera
  id: Camera
  parent: SzeneGenerator.WorldSettings
  langs:
  - csharp
  - vb
  name: Camera
  nameWithType: WorldSettings.Camera
  fullName: SzeneGenerator.WorldSettings.Camera
  type: Property
  source:
    href: https://github.com/ITWascht/exerciseWithCode/blob/b0d4e8cb2a5a6402a319b3d584856e1ffc355b58/Scripts/World/WorldSettings.cs
  assemblies:
  - exerciseWithCode
  namespace: SzeneGenerator
  syntax:
    content: public CameraSettings Camera { get; set; }
    parameters: []
    return:
      type: SzeneGenerator.CameraSettings
    content.vb: Public Property Camera As CameraSettings
  overload: SzeneGenerator.WorldSettings.Camera*
references:
- uid: SzeneGenerator
  commentId: N:SzeneGenerator
  isExternal: true
  href: SzeneGenerator.html
  name: SzeneGenerator
  nameWithType: SzeneGenerator
  fullName: SzeneGenerator
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SzeneGenerator.WorldSettings.#ctor*
  commentId: Overload:SzeneGenerator.WorldSettings.#ctor
  isExternal: true
  href: SzeneGenerator.WorldSettings.html#SzeneGenerator_WorldSettings__ctor
  name: WorldSettings
  nameWithType: WorldSettings.WorldSettings
  fullName: SzeneGenerator.WorldSettings.WorldSettings
  nameWithType.vb: WorldSettings.New
  fullName.vb: SzeneGenerator.WorldSettings.New
  name.vb: New
- uid: SzeneGenerator.WorldSettings.Terrain*
  commentId: Overload:SzeneGenerator.WorldSettings.Terrain
  isExternal: true
  href: SzeneGenerator.WorldSettings.html#SzeneGenerator_WorldSettings_Terrain
  name: Terrain
  nameWithType: WorldSettings.Terrain
  fullName: SzeneGenerator.WorldSettings.Terrain
- uid: SzeneGenerator.TerrainSettings
  commentId: T:SzeneGenerator.TerrainSettings
  parent: SzeneGenerator
  isExternal: true
  href: SzeneGenerator.TerrainSettings.html
  name: TerrainSettings
  nameWithType: TerrainSettings
  fullName: SzeneGenerator.TerrainSettings
- uid: SzeneGenerator.WorldSettings.Sky*
  commentId: Overload:SzeneGenerator.WorldSettings.Sky
  isExternal: true
  href: SzeneGenerator.WorldSettings.html#SzeneGenerator_WorldSettings_Sky
  name: Sky
  nameWithType: WorldSettings.Sky
  fullName: SzeneGenerator.WorldSettings.Sky
- uid: SzeneGenerator.GlobalSkySettings
  commentId: T:SzeneGenerator.GlobalSkySettings
  parent: SzeneGenerator
  isExternal: true
  href: SzeneGenerator.GlobalSkySettings.html
  name: GlobalSkySettings
  nameWithType: GlobalSkySettings
  fullName: SzeneGenerator.GlobalSkySettings
- uid: SzeneGenerator.WorldSettings.Camera*
  commentId: Overload:SzeneGenerator.WorldSettings.Camera
  isExternal: true
  href: SzeneGenerator.WorldSettings.html#SzeneGenerator_WorldSettings_Camera
  name: Camera
  nameWithType: WorldSettings.Camera
  fullName: SzeneGenerator.WorldSettings.Camera
- uid: SzeneGenerator.CameraSettings
  commentId: T:SzeneGenerator.CameraSettings
  parent: SzeneGenerator
  isExternal: true
  href: SzeneGenerator.CameraSettings.html
  name: CameraSettings
  nameWithType: CameraSettings
  fullName: SzeneGenerator.CameraSettings
